<div class="row">

    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Post
                    <span style="float: right;"><a class="" href="<?php echo $this->url('base') ?>"><<< Back</a></span>
                </h3>
            </div>

            <div class="panel-body">

                <?php

                $form = $this->form;
                $form->setAttribute('action', $this->url('base/edit', array(), true));
                $form->prepare();

                $form->get('submit')->setValue('Update Post');

                echo $this->form()->openTag($form);

                echo $this->formCollection($form);

                echo $this->form()->closeTag();

                ?>

            </div>

        </div>

    </div>

</div>
