<div class="row">

    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">View Post
                    <span style="float: right;"><a class="" href="<?php echo $this->url('base') ?>"><<< Back</a></span>
                </h3>
            </div>

            <div class="panel-body">

                <dl>
                    <dt>Post Title</dt>
                    <dd><?php echo $this->escapeHtml($this->post->getTitle());?></dd>
                    <dt>Post Text</dt>
                    <dd><?php echo $this->escapeHtml($this->post->getText());?></dd>
                </dl>

            </div>

        </div>

    </div>

</div>

