
<?php echo $this->partial('layout/search'); ?>

<div class="row">

    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Posts
                    <span style="float: right;"><a class="" href="<?php echo $this->url('base/add') ?>">Add new</a></span>
                </h3>

            </div>

            <div class="panel-body">

                <table id="posts_table" class="table">

                    <tr class="post_header">
                        <th>Title</th>
                        <th>Actions</th>
                    </tr>

                <?php foreach ($this->posts as $post): ?>

                    <tr class="post_row">
                        <td>
                            <span id="post<?php echo $post->getId(); ?>"><?php echo $post->getTitle(); ?></span>
                        </td>
                        <td>
                            <a class="btn btn-success" href="<?php echo $this->url('base/detail', ['id' => $post->getId()]) ?>">View</a>
                            <a class="btn btn-primary" href="<?php echo $this->url('base/edit', ['id' => $post->getId()]) ?>">Edit</a>
                            <a class="btn btn-danger" href="<?php echo $this->url('base/delete',['id' => $post->getId()]) ?>">Delete</a>
                        </td>
                    </tr>

                <?php endforeach ?>

                </table>

                <a id="reset_posts" class="btn btn-success" href="<?php echo $this->url('base') ?>" style="display: none;">Show all posts</a>

            </div>

        </div>

    </div>

</div>

