<?php
/**
 * Price Partial
 *
 * @var \classes\calculation\client\model\tariff\pkv        $this->tariff
 * @var \classes\calculation\mclient\model\parameter\pkv    $this->parameter
 */
$is_child = ($this->parameter->get_insured_person() === 'child');
$is_servant_child = ($this->parameter->get_insured_person() === 'child' && $this->parameter->get_parent_servant_or_servant_candidate() === 'yes');
$is_employee = ($this->parameter->get_profession() === 'employee');
?>
<?php if ($is_employee && !$is_child): ?>
    <div class="wrapper-employee-part">
        <span class="employee-part"><?php echo $this->currencyformat($this->tariff->get_paymentperiod_size_net_contribution()) ?></span>
        <span class="employee-part-text">Ihr Anteil pro Monat</span>
    </div>

    <?php if($this->tariff->get_paymentperiod_size_net_saving() > 0) : ?>
        <div class="wrapper-saving-price">
            <span class="saving-price"><?php echo $this->currencyformat($this->tariff->get_paymentperiod_size_net_saving_per_year()) ?></span>
            <span class="saving-price-text">gespart</span>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="wrapper-employee-part">
        <span class="not-empoyee-part"><?php echo $this->currencyformat($this->tariff->get_paymentperiod_size()); ?></span>
        <span class="employee-part-text">Beitrag pro Monat</span>
    </div>
<?php endif; ?>
