<?php

$error_messages = $element->getMessages();
$info_width_class = 'has_info';

if (empty($help_info)) {
    $info_width_class = '';
}
?>

<div class="c24-content-row <?php if (!empty($help_info)) echo 'c24-content-row-info'; ?> <?php if (!empty($error_messages)) echo 'c24-content-row-error'; ?>" id="<?php echo htmlspecialchars($element->getName()); ?>_container_android" style="<?php if ($visible == false) echo 'display: none'; ?>">

    <div class="c24-content-row-block">

        <label for="<?php echo $element->getName(); ?>" class="c24-label">
            <?php echo $label; ?>
        </label>

        <div class="<?php if (!empty($help_info)) { echo 'c24-content-row-info-content'; } ?> c24-input-content clearfix">

            <div class="ui-input-text ui-body-inherit ui-shadow-inset ui-input-has-clear <?php echo $info_width_class?>">
                <?php
                    echo $content;
                    echo $this->partial('includes/errorinfo.phtml', ['error_messages' => $error_messages]);
                ?>
            </div>

            <?php if (!empty($help_info)): ?>
                <div class="c24-content-row-info-icon js-c24-info-icon">
                    <div class="c24-info-icon">?</div>
                </div>
            <?php endif; ?>

        </div>

    </div>

    <?php

    if (!empty($help_info)) {
        echo $this->partial('includes/helpinfo.phtml', ['help_info_content' => $help_info['content'], 'help_info_hint' => null]);
    }

    ?>

</div>
