<?php
    $options = $element->getValueOptions();
    $error_messages = $element->getMessages();
?>

<div class="c24-content-row c24-select-container <?php if (!empty($help_info)) echo 'c24-content-row-info'; ?> <?php if (!empty($error_messages)) echo 'c24-content-row-error'; ?> c24-clearfix" id="<?php echo htmlspecialchars($element->getName()); ?>_container" style="<?php if ($visible == false) echo 'display: none'; ?>">

    <div class="c24-content-row-block">

        <label id="<?php echo $element->getAttribute('data-headline'); ?>" for="<?php echo htmlspecialchars($element->getName()); ?>" class="js-c24-block-label-top c24-label <?php if ($element->getValue() != '') { echo 'c24-input-title-visible'; } ?>">
            <?php echo $label; ?>
        </label>


        <div class="<?php if (!empty($help_info)) { echo 'c24-content-row-info-content'; } ?> c24-select">

            <a href="javascript:void(0)" role="button" id="<?php echo htmlspecialchars($element->getName()); ?>-select-button" data-name="<?php echo htmlspecialchars($element->getName()); ?>" class="c24-select-button ui-btn ui-icon-carat-d ui-btn-icon-right ui-corner-all ui-shadow <?php if (!empty($error_messages)) echo 'c24-form-errorbox'; ?>" >
                <span>
                    <?php echo isset($options[$element->getValue()]) ? $options[$element->getValue()] : $options[key($options)]; ?>
                </span>
            </a>

            <?php echo $content; ?>

        </div>

        <?php if (!empty($help_info)): ?>
            <div class="c24-content-row-info-icon js-c24-info-icon">
                <div class="c24-info-icon">?</div>
            </div>
        <?php endif; ?>
    </div>

    <?php

        if (!empty($help_info)) {
            echo $this->partial('includes/helpinfo.phtml', ['help_info_content' => $help_info['content'], 'help_info_hint' => $hint]);
        }

        if (!empty($error_messages)) {
            echo $this->partial('includes/errorinfo.phtml', ['error_messages' => $error_messages]);
        }

    ?>

</div>

<div class="c24-selectmenu" id="<?php echo htmlspecialchars($element->getName()); ?>-listbox-popup" tabindex="0" data-name="<?php echo htmlspecialchars($element->getName()); ?>">

    <ul>

        <?php $count = count($element->getValueOptions()); $i = 1; ?>

        <?php foreach ($element->getValueOptions() as $value => $content): ?>

            <li data-option-value="<?php echo $value ?>" class="ui-child <?php if ($i == 1) echo 'c24-first-child' ?> <?php if ($i == $count) echo 'c24-last-child' ?>" role="option">
                <a href="javascript:void(0)" tabindex="-100" class="ui-btn"><?php echo $content; ?></a>
            </li>

        <?php $i++; endforeach; ?>

    </ul>

</div>
