<?php

if ($form->has('agb_read')) {
    echo $this->form()->openTag($form);
    echo $this->form->render($this->form->generate_hidden_field('agree'));
}

?>

<div class="c24-form-start" id="c24-register-overview">

<div class="c24-form-element-group">

<br><br>
<div class="c24-form-element-center">
    <b>Der gewählte Tarif steht aufgrund interner Richtlinien von ExtraEnergie nicht zur Verfügung.
    Gerne können Sie über unser Portal erneut vergleichen und einen alternativen Tarif wählen.</b>

    <br><br>
    <a class="c24-button-plain-blue" href="<?php echo $register_link;?>">« zurück zum Ergebnis</a>

</div>

</div>

<?php
if ($form->has('agb_read')) :
    ?>

<div id="c24-important-field-info">
    * Pflichtfeld
</div>

<?php
    echo $this->form()->closeTag($form);
endif;

echo $generaltracking_pixel;
