<?php
    echo $this->form()->openTag($form);

    if (!isset($address_data['company'])) {
        $address_data['company'] = '';
    }

    if (!isset($accountowner_self_data['accountowner_company'])) {
        $accountowner_self_data['accountowner_company'] = '';
    }

    if (!isset($accountowner_self_data['accountowner_email'])) {
        $accountowner_self_data['accountowner_email'] = '';
    }

?>

<div class="c24-form-start">

    <div class="c24-form-element-group">

        <?php

            $value_options = $form->get('paymenttype')->getValueOptions();

            if (count($value_options) == 2 || $value_options[0]['value'] != 'transfer') {
                echo '<span class="c24-register-infotext">Ihre Zahlungsdaten</span>';
            }

            echo $this->form->render($this->form->generate_radio_field('paymenttype', '', array(), count($value_options) == 2));

            echo '<div id="c24-register-bank-directdebit" ' . ($form->get('paymenttype')->getValue() == 'transfer' ? 'style="display: none;"' : '') .'>';

            $bank_options = $this->form->get('banktype')->getValueOptions();
            if (count($bank_options) == 2 ) {
                echo $this->form->render($this->form->generate_radio_field('banktype', 'Bankdaten', array(), true, array('title' => 'Ihre Bankdaten', 'content' => 'Bitte geben Sie Ihre Bankdaten mit Hilfe von IBAN, oder Ihrer bisher gewohnten Kontonummer und Bankleitzahl ein.')));
            }

            echo '<div id="c24-register-bank-classic" ' . ($form->get('banktype')->getValue() == 'classic' ? '' : 'style="display: none;"') . '>';

            if ($this->form->has('accountnumber')) {
                echo $this->form->render($this->form->generate_tel_field('accountnumber', 'Kontonummer *', array(), true, array('title' => 'Kontonummer', 'content' => 'Bitte geben Sie Ihre Kontonummer ohne Leerzeichen ein.')));
            }

            if ($this->form->has('bankcode')) {

                echo '<div id="c24-bank-container">';

                echo $this->form->render($this->form->generate_tel_field('bankcode', 'Bankleitzahl *', array('maxlength' => '8'), true, array('title' => 'Bankleitzahl', 'content' => 'Die Bankleitzahl ist immer 8-stellig. Bitte geben Sie die Bankleitzahl ohne Leerzeichen ein.')));
                echo '<span id="c24-bank-name"></span>';

                echo '</div>';

            }

            echo '</div>';
            echo '<div id="c24-register-bank-sepa" ' . ($form->get('banktype')->getValue() == 'sepa' ? '' : 'style="display: none;"') . '>';

            if ($this->form->has('iban')) {
                echo $this->form->render($this->form->generate_text_field('iban', 'IBAN *', array(), true, array('title' => 'IBAN', 'content' => 'Die IBAN ist eine neue, international standardisierte Kontonummer, die in Deutschland 22-stellig ist und künftig jedem Konto zugeordnet und in Zukunft die bisherige Kontonummer ablösen wird. Wenn Ihnen Ihre IBAN derzeit nicht bekannt ist, können Sie vorerst auch weiterhin wie gewohnt Ihre Kontonummer und Bankleitzahl angeben.')));
                echo '<span id="c24-bank-name-sepa"></span>';
            }

            echo '</div>';


            if ($this->form->has('debt_order')) {
                echo $this->form->render($this->form->generate_checkbox_field('debt_order', 'Einzugsermächtigung zustimmen'));
            }

            if ($allow_alternative_accountowner == true) {

                if ($this->form->has('accountowner_type')) {

                    echo $this->form->render($this->form->generate_radio_field(
                        'accountowner_type',
                        'Kontoinhaber',
                        [],
                        true,
                        ['content' => 'Bitte wählen Sie aus, ob Sie als Antragssteller selbst der Inhaber des oben genannten Kontos sind oder ob der Kontoinhaber vom Antragssteller abweicht.']
                    ));

                }
                $notoggleclass = '';

                echo '<div id="accountowner_toggle">';

                if ($show_company == true) {
                    echo '<input type="hidden" id="is_business_tariff" value="1" />';
                } else {
                    echo '<input type="hidden" id="is_business_tariff" value="0" />';
                }

                if ($this->form->has('accountowner_gender')) {
                    echo $this->form->render($this->form->generate_select_field('accountowner_gender', 'Anrede *', array(), true, array('title' => 'Adressdaten des Kontoinhabers', 'content' => 'Bitte wählen Sie eine Anrede aus.')));
                }

                if ($show_company == true) {
                    if ($this->form->has('accountowner_company')) {
                        echo $this->form->render($this->form->generate_text_field('accountowner_company', 'Firmenname *', array(), true, array('title' => 'Kontoinhaber', 'content' => 'Bitte geben Sie den Kontoinhaber an.')));
                    }
                }

                if ($this->form->has('accountowner_firstname')) {
                    echo $this->form->render($this->form->generate_text_field('accountowner_firstname', 'Vorname *', array(), true, array('title' => 'Kontoinhaber Vorname', 'content' => 'Bitte geben Sie den Vornamen des Kontoinhabers an.')));
                }

                if ($this->form->has('accountowner_lastname')) {
                    echo $this->form->render($this->form->generate_text_field('accountowner_lastname', 'Nachname *', array(), true, array('title' => 'Kontoinhaber Nachname', 'content' => 'Bitte geben Sie den Nachnamen des Kontoinhabers an.')));
                }

                if ($this->form->has('accountowner_zipcode')) {
                    ?>

                    <div id="address_fields_container">

                        <div class="c24-clearfix c24-twocolumn-info">

                            <div class="c24-clearfix">

                                <div class="c24-twocolumn-input">

                                    <div class="c24-register-field-50">
                                        <?php echo $this->form->render($this->form->generate_tel_field('accountowner_zipcode', 'PLZ *', array('maxlength' => 5), true)); ?>
                                    </div>
                                    <div class="c24-register-field-50 c24-register-field-last" style="padding-left: 0px;">
                                        <?php

                                        if ($form->get('accountowner_city')->getAttribute('type') == 'select') {
                                            echo $this->form->render($this->form->generate_select_field('accountowner_city', 'Ort *', array(), true));
                                        } else {
                                            echo $this->form->render($this->form->generate_text_field('accountowner_city', 'Ort *', array('readonly' => 'readonly'), true));
                                        }

                                        ?>
                                    </div>

                                </div>

                                <div class="c24-content-row-info-icon">
                                    <div class="c24-info-icon">?</div>
                                </div>

                            </div>

                            <?php echo $this->partial('mobile/fields/includes/helpinfo.phtml', ['help_info_content' => 'Bitte geben Sie die Adressdaten des Kontoinhabers an.']); ?>

                        </div>

                        <div class="c24-clearfix c24-twocolumn-info">

                            <div class="c24-clearfix">

                                <div class="c24-twocolumn-input">

                                    <div class="c24-register-field-70">
                                        <?php echo $this->form->render($this->form->generate_select_field('accountowner_street', 'Straße *', array(), true)); ?>
                                    </div>
                                    <div class="c24-register-field-30 c24-register-field-last" style="padding-left: 0px;">
                                        <?php echo $this->form->render($this->form->generate_text_field('accountowner_streetnumber', 'Nr *', array(), true)); ?>
                                    </div>

                                </div>

                                <div class="c24-content-row-info-icon">
                                    <div class="c24-info-icon">?</div>
                                </div>

                            </div>

                            <?php echo $this->partial('mobile/fields/includes/helpinfo.phtml', ['help_info_content' => 'Bitte geben Sie die Adressdaten des Kontoinhabers an.']); ?>

                        </div>

                    </div>

                <?php

                    if ($this->form->has('accountowner_email')) {
                        echo $this->form->render($this->form->generate_email_field('accountowner_email', 'E-Mail', array(), true, array('title' => 'E-Mail', 'content' => 'Bitte geben Sie eine E-Mail-Adresse des Kontoinhabers an.')));
                    }

                    if ($allow_alternative_accountowner) {

                        if ($this->form->has('alternative_accountowner_auth')) {

                            if ($this->form->get('accountowner_type')->getValue() == 'self') {
                                echo $this->form->render($this->form->generate_checkbox_field('alternative_accountowner_auth', $bank_auth_text_debit_auth, array(), false, array('title' => '', 'content' => 'Sollten Sie nicht selbst der Kontoinhaber sein, versichern Sie bitte zusätzlich, dass Sie vom Kontoinhaber eine Vollmacht zur Erteilung der Einzugsermächtigung besitzen.')));
                            } else if ($this->form->get('accountowner_type')->getValue() == 'other') {
                                echo $this->form->render($this->form->generate_checkbox_field('alternative_accountowner_auth', $bank_auth_text_debit_auth, array(), true, array('title' => '', 'content' => 'Sollten Sie nicht selbst der Kontoinhaber sein, versichern Sie bitte zusätzlich, dass Sie vom Kontoinhaber eine Vollmacht zur Erteilung der Einzugsermächtigung besitzen.')));
                            }



                        }

                    }

                }

                echo '</div>';

            }

            if ($this->form->has('bank_auth_sepa')) {

                $head_line = 'Erteilung des SEPA-Lastschriftmandates für die ' . $provider_name;

                $content = '<br/><b>Name</b> ' . $provider_name;
                $content .= '<br><b>Adresse</b> ' . $provider_address;
                $content .= '<br><b>Gläubiger-Identifikationsnummer</b> ' . $provider_creditor;
                $content .= '<br><b>Mandatsreferenz</b> Erhalten Sie mit den ' . ($product_id == 1 ? 'Stromunterlagen' : 'Gasunterlagen');

                $content .= '<br><br>' . $bank_auth_overlay_sepa . '<br><br>';

                if (isset($bank_auth_overlay_info)) {
                    $content .= $bank_auth_overlay_info;
                }

                if (isset($bank_auth_overlay_info_business)) {
                    $content .= $bank_auth_overlay_info_business;
                }

                $content .= '<br><br><b>Kontoinhaber</b>';
                $content .= ' <span id="overlay_firstname">' . $accountowner_self_data['accountowner_firstname'] . '</span>';
                $content .= ' <span id="overlay_lastname">' . $accountowner_self_data['accountowner_lastname'] . '</span>';
                $content .= ' <span id="overlay_company">' . $accountowner_self_data['accountowner_company'] . '</span>';
                $content .= '<br><b>Straße, Hausnummer</b>';
                $content .= ' <span id="overlay_street">' . $accountowner_self_data['accountowner_street'] . '</span>';
                $content .= ' <span id="overlay_streetnumber">' . $accountowner_self_data['accountowner_streetnumber'] . '</span>';
                $content .= '<br><b>PLZ, Ort</b>';
                $content .= ' <span id="overlay_zipcode">' . $accountowner_self_data['accountowner_zipcode'] . '</span>';
                $content .= ' <span id="overlay_city">' . $accountowner_self_data['accountowner_city'] . '</span>';
                $content .= '<br><span id="overlay_bankname"><b>Kreditinsitut</b> Bitte geben Sie Ihre Bankdaten ein.</span>';
                $content .= '<br><span id="overlay_bic"><b>BIC</b> Bitte geben Sie Ihre Bankdaten ein.</span>';
                $content .= '<br><span id="overlay_iban"><b>IBAN</b> Bitte geben Sie Ihre Bankdaten ein.</span>';

                echo $this->form->render($this->form->generate_checkbox_field('bank_auth_sepa', $bank_auth_text_sepa, array(), true, array('title' => $head_line, 'content' => $content)));
            }

            echo '<br/><ul class="c24-checkmark-list"><li>Abbuchung erfolgt nur, wenn ein ';
            if ($this->layout()->tariff->get_tariff_product_id() == 1) { echo 'Strom'; } else { echo 'Gas'; }
            echo '-Vertrag auch zustande kommt.</li></ul>';

            echo '</div>';

            echo '<div id="c24-register-bank-transfer" ' . ($form->get('paymenttype')->getValue() != 'transfer' ? 'style="display: none;"' : '') .'>';

            echo '<span class="c24-register-infotext">Zahlung per Überweisung</span>';
            echo '<ul class="c24-checkmark-list">';

            echo '<li>Rechnungen bzw. Abschläge selbst überweisen </li>';

            if ($this->layout()->tariff->get_payment_transfer_cost_once() > 0 || $this->layout()->tariff->get_payment_transfer_cost_monthly() > 0) {

                if ($this->layout()->tariff->get_payment_transfer_cost_once() > 0) {
                    echo '<li>Zusatzkosten von ' .  number_format($this->layout()->tariff->get_payment_transfer_cost_once() / 100, 2, ',', '.') . ' € einmalig</li>';
                } else {
                    echo '<li>Zusatzkosten von ' .  number_format($this->layout()->tariff->get_payment_transfer_cost_monthly() / 100, 2, ',', '.') . ' € monatlich</li>';
                }

            } else {
                echo '<li>Keine Zusatzkosten</li>';
            }

            echo '</ul>';
            echo '</div>';

        ?>

    </div>

    <div class="c24-form-element-center">
        <input type="submit" id="submit_button" value="weiter" class="c24-button-plain-blue full_button">
    </div>

</div>

<?php
    echo $this->form()->closeTag();
?>

<div id="c24-important-field-info">
    * Pflichtfeld
</div>

<script type="text/javascript">

    var link_ajax_json_bankname = '<?php echo $link_ajax_json_bankname; ?>';

    var accountowner_preloaded = {
        gender:       '<?php echo $accountowner_self_data["accountowner_gender"]; ?>',
        company:      '<?php echo $accountowner_self_data["accountowner_company"]; ?>',
        firstname:    '<?php echo $accountowner_self_data["accountowner_firstname"]; ?>',
        lastname:     '<?php echo $accountowner_self_data["accountowner_lastname"]; ?>',
        zipcode:      '<?php echo $accountowner_self_data["accountowner_zipcode"]; ?>',
        city:         '<?php echo $accountowner_self_data["accountowner_city"]; ?>',
        street:       '<?php echo $accountowner_self_data["accountowner_street"]; ?>',
        streetnumber: '<?php echo $accountowner_self_data["accountowner_streetnumber"]; ?>',
        email:        '<?php echo $accountowner_self_data["accountowner_email"]; ?>'
    };

    <?php if ($allow_alternative_accountowner === true): ?>

    var address_data = {
        gender:       '<?php echo $address_data["gender"]; ?>',
        company:      '<?php echo $address_data["company"]; ?>',
        firstname:    '<?php echo $address_data["firstname"]; ?>',
        lastname:     '<?php echo $address_data["lastname"]; ?>',
        zipcode:      '<?php echo $address_data["zipcode"]; ?>',
        city:         '<?php echo $address_data["city"]; ?>',
        street:       '<?php echo $address_data["street"]; ?>',
        streetnumber: '<?php echo $address_data["streetnumber"]; ?>',
        email:        '<?php echo $address_data["email"]; ?>'
    };

    var accountowner_current = {
        gender:       '<?php if ($this->form->has("accountowner_gender")) echo $form->get("accountowner_gender")->getValue(); ?>',
        company:      '<?php if ($this->form->has("accountowner_company")) echo $form->get("accountowner_company")->getValue(); ?>',
        firstname:    '<?php if ($this->form->has("accountowner_firstname")) echo $form->get("accountowner_firstname")->getValue(); ?>',
        lastname:     '<?php if ($this->form->has("accountowner_lastname")) echo $form->get("accountowner_lastname")->getValue(); ?>',
        zipcode:      '<?php if ($this->form->has("accountowner_zipcode")) echo $form->get("accountowner_zipcode")->getValue(); ?>',
        city:         '<?php if ($this->form->has("accountowner_city")) echo $form->get("accountowner_city")->getValue(); ?>',
        street:       '<?php if ($this->form->has("accountowner_street")) echo $form->get("accountowner_street")->getValue(); ?>',
        streetnumber: '<?php if ($this->form->has("accountowner_streetnumber")) echo $form->get("accountowner_streetnumber")->getValue(); ?>',
        email:        '<?php if ($this->form->has("accountowner_email")) echo $form->get("accountowner_email")->getValue(); ?>'
    };
    <?php endif; ?>

    <?php if (isset($diff_address_data_sso_data) && $diff_address_data_sso_data): ?>
        var comes_from_sso = true;
    <?php else: ?>
        var comes_from_sso = false;
    <?php endif; ?>

    <?php if (!in_array($this->layout()->tariff->get_provider_id(), [11290, 11129, 11038, 11317, 12127, 12128])): ?>
        var remove_previous_step = true;
    <?php else: ?>
        var remove_previous_step = false;
    <?php endif; ?>

</script>