<?php
    echo $this->form()->openTag($form);
?>

<div class="c24-form-start">

    <div class="c24-form-element-group">

        <span class="c24-register-infotext">Passwort vergessen</span>

        <p>
            Sie erhalten eine E-Mail mit einem Link, über den Sie sich ein neues Passwort anlegen können.
        </p>

        <?php

            echo $this->form->render($this->form->generate_email_field('email', 'E-Mail-Adresse *', array('id' => 'email', 'placeholder' => 'E-Mail-Adresse *', 'class' => 'c24-form-text'), true));

            $month = date("m");
            $day = date("d");
            $year = date("Y") - 18;
            $maxdate = $day.'.'.$month.'.'.$year;

            echo $this->form->render($this->form->generate_date_field('birthdate', 'Geburtsdatum *', array('max' => $maxdate)));

        ?>

    </div>

    <div class="c24-form-element-center">
        <input type="submit" value="Passwort neu anfordern" class="c24-button-plain-blue full_button">
    </div>

    <div class="c24-form-element-group">

        <span id="c24-c24login-promo-text">
            Passworthilfe:
        </span>

        <ul class="c24-checkmark-list">
            <li>Sie bekommen eine E-Mail mit einem Link zum Passwort zurücksetzen.</li>
        </ul>

    </div>

</div>

<?php
    echo $this->form()->closeTag();
?>

<div id="c24-important-field-info">
    * Pflichtfeld
</div>