<div id="c24-register-converted">
    <div class="blocker" id="blocker">
        <i class="fa fa-spinner fa-spin fa-5x" id="blocker-icon"></i>
    </div>
    <div id="c24-register-converted-infos">

        <div id="c24-converted-thx">
            <div id="c24-register-converted-text">
                <span id="c24-converted-thx-title">Vielen Dank</span>
            </div>
        </div>

        <div class="c24-register-thank_info_wrapper">

            <?php if($this->layout()->subscriptiontype == 'offer'): ?>
                Wir haben Ihre Anfrage erhalten.
            <?php else: ?>
                <p>Wir haben Ihre Anfrage erhalten und melden uns umgehend bei Ihnen.</p>
            <?php endif; ?>

            <p>Ihre Anfragenummer: <b id="offer_id"><?php echo $this->offer_id ?></b></p>
        </div>

        <div id="optimize_tariff_choice" class="working_hours">
            <span class="headline">Jetzt Tarifauswahl optimieren</span>
            <a href="tel:089 - 24 24 12 72" class="phone_thank ui-link">089 - 24 24 12 72</a>
            <a href="mailto:pkv@check24.de" class="mail_thank">pvk@check24.de</a>
            <div class="user_signature"><span class="user"></span>, Experte für private Krankenversicherung</div>
        </div>

        <div class="thank_you_content">
            <span id="c24-converted-next-steps-toggle">So geht es weiter</span>

            <ul id="c24-converted-next-steps">

                <li class="clearfix">
                    <div class="thx-number-first"></div>
                    <div class="text">

                        <?php if($this->layout()->subscriptiontype=='offer'): ?>
                            <h1>Ihr Angebot</h1>
                            <img src="/massets/images/styleguide/Icon_Brief-offen.png" class="icons_mail_post">
                            <p>
                            <span class="no_working_hours">Unsere Experten für private Krankenversicherung prüfen </span>
                            <span class="working_hours"><span class="user"></span>, Experte für private Krankenversicherung, prüft </span>
                            Ihren gewählten Tarif und <span class="no_working_hours">senden</span><span class="working_hours">sendet</span> Ihnen in Kürze ein Angebot zu - kostenfrei und unverbindlich; bei Rückfragen melden wir uns bei Ihnen telefonisch.
                            </p>
                        <?php else: ?>
                            <h1>Persönliche Beratung</h1>
                            <img src="/massets/images/styleguide/persoenlich-versichern-01.png" class="icons_mail_post">
                            <p>
                            <span class="no_working_hours">Ihr persönlicher Experte für private Krankenversicherung </span>
                            <span class="working_hours"><span class="user"></span>, Experte für private Krankenversicherung, </span>
                            berät Sie telefonisch.
                            </p>
                        <?php endif; ?>

                    </div>

                </li>

                <li class="clearfix">

                    <div class="thx-number-second"></div>
                    <div class="text">
                        <h1>In Ruhe prüfen</h1>
                        <img src="/massets/images/styleguide/vielen-dank-02.png" class="icons_mail_post">
                        <p>

                            <?php if($this->layout()->subscriptiontype=='offer'): ?>
                        <div class="no_working_hours">
                            Haben Sie Fragen? Wünschen Sie weitere Beratung? Unsere Experten für private Krankenversicherung sind für Sie gerne unter <a class="phone_thank" href="tel:089 - 24 24 12 72">089 - 24 24 12 72</a> da.
                        </div>
                        <div class="working_hours">Prüfen Sie Ihr Angebot in Ruhe. Bei Fragen sind wir für Sie da.</div>
                        <?php else : ?>
                            Sie erhalten Ihr persönliches Angebot schriftlich kostenfrei und unverbindlich.
                            <span class="no_working_hours">
                                Ihr Experte für private Krankenversicherung
                            </span>
                            <span class="working_hours">
                                <span class="user"></span>
                            </span>
                            unterstützt Sie bei allen weiteren Fragen.
                        <?php endif; ?>

                        </p>
                    </div>

                </li>

                <li class="clearfix">

                    <div class="thx-number-third"></div>
                    <div class="text">
                        <h1>Einfach beantragen</h1>
                        <img src="/massets/images/styleguide/so-einfach-versichern-03.png" class="icons_mail_post">
                        <p>Senden Sie uns den ausgefüllten Antrag einfach zurück. Wir kümmern uns um den Rest!</p>
                    </div>

                </li>

            </ul>

            <div class="any_questions">

                <span id="c24-converted-next-steps-toggle">Noch Fragen?</span>

                <div class="content clearfix">
                    <p>Sie erreichen unsere Experten für private Krankenversicherung <br/> Mo. bis So. 8:00 - 20:00 Uhr unter <br/><a class="phone_thank" href="tel:089 - 24 24 12 72">089 - 24 24 12 72</a><span class="content-email"> oder per E-Mail an <br/><a href="mailto:pkv@check24.de">pkv@check24.de</a></span></p>
                    <p>Bitte nennen Sie dazu Ihre Anfragenummer:&nbsp;<b><?php echo $this->offer_id ?></b></p>
                    <p>Die Beratung ist kostenfrei und unverbindlich für Sie.</p>
                </div>

            </div>
        </div>
    </div>

    <?php echo $this->partial('mobile/register/cross_selling.phtml', ['lead' => $this->lead]);
    $this->headScript()->appendFile('https:' . $this->cct_loader . '/loader', 'text/javascript');
    ?>

</div>
