<?php

    if ($form->has('agb_read')) {
        echo $this->form()->openTag($form);
        echo $this->form->render($this->form->generate_hidden_field('agree'));
    }
?>

<div class="c24-form-start" id="c24-register-overview">

    <div class="c24-form-element-group">

        <span class="c24-register-infotext">Sicherheitsleistung ca. <?php echo $creditcheckstrategyparameters[0]; ?> <?php echo $creditcheckstrategyparameters[1]; ?></span>



        <div id="c24-register-unfinished-info" class="c24-register-debit-info">
            Leider kann die <?php if($registertariff->get_provider_company() != '') { echo htmlspecialchars($registertariff->get_provider_company()); } else if($registertariff->get_provider_brand() != '') { echo htmlspecialchars($registertariff->get_provider_brand()); } else { echo htmlspecialchars($registertariff->get_provider_name()); } ?> Ihnen diesen Tarif aufgrund interner Richtlinien nicht zu den ursprünglichen Konditionen anbieten.
        </div>

        <div id="c24-register-unfinished-info" class="c24-register-debit-info">
            Alternativ bietet Ihnen die <?php if($registertariff->get_provider_company() != '') { echo htmlspecialchars($registertariff->get_provider_company()); } else if($registertariff->get_provider_brand() != '') { echo htmlspecialchars($registertariff->get_provider_brand()); } else { echo htmlspecialchars($registertariff->get_provider_name()); } ?> folgende Tarifvariante an, die sich <b>nur</b> im Rahmen einer notwendigen Kautionszahlung zu dem von Ihnen ursprünglich gewünschten Tarif unterscheidet (siehe unten).
        </div>

        <div id="c24-register-unfinished-info" class="c24-register-debit-info">
            Beachten Sie bitte, dass Sie durch die <?php if($registertariff->get_provider_company() != '') { echo htmlspecialchars($registertariff->get_provider_company()); } else if($registertariff->get_provider_brand() != '') { echo htmlspecialchars($registertariff->get_provider_brand()); } else { echo htmlspecialchars($registertariff->get_provider_name()); } ?> nur dann erfolgreich beliefert werden können, sofern der Kautionsbetrag von ca. <?php echo intval($debit_euro); ?> € von Ihrem Konto eingezogen werden kann. Der voraussichtliche Einzug erfolgt frühstens zum <?php $datea = explode('.', $debit_date); echo $datea[1] . '.' . $datea[0] . '.' . $datea[2]; ?>.
        </div>

        <div id="c24-register-unfinished-info" class="c24-register-debit-info">
            Wenn Sie diesen Vertrag abschließen wollen, drücken Sie bitte aud "Kauf abschließen"
        </div>


        <span class="c24-register-infotext">Zusammenfassung Ihrer Angaben</span>




        <div class="c24-register-overview-container">

            <span class="c24-register-overview-headline">
                Tarifdetails
            </span>

            <div class="c24-register-overview-group c24-clearfix">
                <strong>
                    <?php

                        echo htmlspecialchars($registertariff->get_provider_name()) . '<br>';

                        if ($registertariff->get_provider_brand() != '') {
                            echo '(Marke der ' . htmlspecialchars($registertariff->get_provider_brand()) . ')<br>';
                        }

                        echo htmlspecialchars($registertariff->get_tariff_name()) . '<br>';

                    ?>
                </strong>
            </div>

            <?php

                for ($i = 0, $i_max = count($tariff_infos); $i < $i_max; ++$i) {


                    echo '<div class="c24-clearfix">

                            <div class="c24-register-ovewview-group-title">
                                <span>' . htmlspecialchars($tariff_infos[$i]['label']) . '</span>
                            </div>

                            <div class="c24-register-ovewview-group-content">
                                ' . htmlspecialchars($tariff_infos[$i]['value']) . '
                            </div>

                        </div>
                    ';


                }

            ?>






        </div>

        <div id="c24-register-unfinished-info" class="c24-register-debit-info-red">
                Kautionszahlung: ca. <?php echo $creditcheckstrategyparameters[0]; ?> <?php echo $creditcheckstrategyparameters[1]; ?>; ca. <?php echo intval($debit_euro); ?> €. Die <?php echo $creditcheckstrategyparameters[2]; ?> erhalten Sie bei ausgeglichenem Kundenkonto ca. 6 Wochen nach Beendigung Ihres Vertrages mit der Endabrechnung zurück.
            </div>

        <div class="c24-register-overview-container">

            <div class="c24-register-overview-group c24-clearfix">
                <span>Sofern nicht ausdrücklich anders ausgewiesen beinhalten alle Preise die gesetzl. MwSt.</span>
            </div>

        </div>

    </div>

    <div class="c24-form-element-center">
        <?php

            if ($form->has('agb_read')) {
                echo '<input type="submit" class="c24-button-plain-blue full_button" value="Angebot anfordern">';
            } else {
                echo '<a class="c24-button-plain-blue full_button" href="' . htmlspecialchars($form->getAttribute('action')) . '?agree=yes&creditcheck_id=' . $creditcheck_id . '">Kauf abschließen</a>';
            }

        ?>
    </div>

</div>

<?php
    echo $generaltracking_pixel;
