<?php
    echo $this->form()->openTag($form);
?>

<div class="c24-form-start">

    <div class="c24-form-element-group">

        <span class="c24-register-infotext">Wichtige Antragsdaten</span>

        <div id="c24-register-unfinished-info">
            <strong>Falls Sie diese Daten gerade nicht zur Hand haben, können Sie die Felder leer lassen.</strong>
            Sobald Sie Ihren Antrag abgeschickt haben, senden wir Ihnen deshalb eine Erinnerung per E-Mail zu, so dass Sie diese Daten nachreichen können. Erst wenn Sie Ihre Angaben vervollständigt haben, können wir Ihren Antrag bearbeiten und an den von Ihnen gewählten Anbieter weiterleiten.
        </div>

        <?php

            if ($form->has('provider')) :

            if (!empty($this->provider_matches)) :

        ?>

        <div class="c24-register-providerchoose-errorbox" id="provider_match_choose_div">

            <span id="c24-register-providerchoose-label">Der gewählte Versorger ist uns nicht bekannt. Meinten Sie:</span>

            <ul id="c24-register-providerchoose-list">

                <?php

                    foreach ($this->provider_matches AS $id => $names) {

                        echo '<li><a class="c24-color" href="javascript: choose_provider_match(\''
                            . $id . '\', \'' . $names[0]
                            . '\');">' . $names[0]
                            . ($names[1] ? ' (' . $names[1] . ')' : '')
                            . '</a></li>' . "\n";

                    }

                ?>

                <li id="c24-register-providerchoose-not-list"><a class="c24-color" href="javascript: choose_provider_no_match();">Nicht in der Liste. Ohne Auswahl weiter.</a></li>

            </ul>

        </div>

        <?php

            endif;
            $star = ($provider_mandatory) ? ' *' : '';
            echo $this->form->render($this->form->generate_text_field(
                'provider',
                'Derzeitiger ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorger ' . $star,
                array(),
                true,
                array(
                    'title' => 'Ihr derzeitiger ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorger',
                    'content' => 'Der ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorger, der Sie derzeit beliefert. Dies ist in der Regel Ihr lokaler ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorger.'
                )
                )
            );

            endif;

            if ($form->has('customernumber')) {
                $star = ($customernumber_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('customernumber', 'Kundennummer' . $star, array(), true, array('title' => 'Kundennummer/Vertragskontonummer', 'content' => 'Die Kundenummer, häufig auch genannt Vertragskontonummer ist auf der Rechnung Ihres jetzigen ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorgers aufgeführt.')));


            }

            $star = ($counter_number_mandatory) ? ' *' : '';
            echo $this->form->render($this->form->generate_text_field('counter_number', 'Zählernummer ' . $star, array(), true, array('title' => 'Zählernummer', 'content' => 'Die Zählernummer finden Sie auf der Rechnung Ihres derzeitigen ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorgers oder aber auf Ihrem ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'zähler. Der ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'zähler befindet sich in der Regel im Keller oder Flur.')));


            if ($form->has('persons')) {
                $star = ($persons_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_tel_field('persons', 'Personen im Haushalt ' . $star, array(), true, array('title' => 'Anzahl der Personen', 'content' => 'Die Anzahl der Personen, die regelmäßig in Ihrem Haushalt leben.')));
            }

            if ($form->has('cancelation_self')) {

                echo $this->form->render(

                    $this->form->generate_radio_field(
                        'cancelation_self',
                        'Beim derzeitigen Versorger gekündigt?',
                        array(),
                        true,
                        array(
                            'title' => 'Haben Sie Ihrem derzeitigen Versorger bereits gekündigt?',
                            'content' => 'Bitte geben Sie an, ob Sie Ihren bestehenden ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Strom' : 'Gas') . 'versorgungsvertrag bereits selbst gekündigt haben.<br><br><b>Wichtig:</b><br>Kündigen Sie Ihren Vertrag nur dann selbst, wenn Sie ein Sonderkündigungsrecht aufgrund einer Preiserhöhung in Anspruch nehmen, oder wenn bei Laufzeitverträgen (Laufzeit länger als drei Monate) Ihre Kündigungsfrist in weniger als vier Wochen abläuft.'
                        )
                    )
                );

                $month = date("m");
                $day = date("d") + 1;
                $year = date("Y");
                $mindate = $day.'.'.$month.'.'.$year;

                echo $this->form->render($this->form->generate_date_field('cancelation_date', 'Kündigungsdatum', array('min' => $mindate), $form->get('cancelation_self')->getValue() == 'yes', array('title' => 'Datum Vertragsende', 'content' => 'Bitte tragen Sie hier den letzten Tag Ihres alten ' . ($this->layout()->tariff->get_tariff_product_id() == 1 ? 'Stromvertrages' : 'Gasvertrages') . ' ein. In der Regel ist dies der letzte Tag eines Monats.')));

            }

            if ($form->has('delivery_self')) {

                $help_text = '';

                if ($this->layout()->tariff->get_tariff_product_id() == 1) {
                    $help_text = 'Bitte geben Sie an, wann die Stromlieferung umgestellt werden soll. Beachten Sie bitte, dass der schnellstmögliche Wechsel abhängig von Kündigungsfrist und Anbieter mehrere Wochen dauern kann. Sollten Sie zu einem späteren Zeitpunkt wechseln wollen (z.B. weil Sie dadurch noch eine Bonuszahlung von Ihrem alten Anbieter erhalten), können Sie dies unter „Wunschtermin“ auswählen.';
                } else {
                    $help_text = 'Bitte geben Sie an, wann die Gaslieferung umgestellt werden soll. Beachten Sie bitte, dass der schnellstmögliche Wechsel abhängig von Kündigungsfrist und Anbieter mehrere Wochen dauern kann. Sollten Sie zu einem späteren Zeitpunkt wechseln wollen (z.B. weil Sie dadurch noch eine Bonuszahlung von Ihrem alten Anbieter erhalten), können Sie dies unter „Wunschtermin“ auswählen.';
                }

                echo $this->form->render(

                    $this->form->generate_select_field(
                        'delivery_self',
                        'Liefertermin',
                        array(),
                        ($form->has('cancelation_self') ? $form->get('cancelation_self')->getValue() == 'no' : true),
                        array(
                            'title' => 'Gewünschter Lieferbeginn',
                            'content' => $help_text
                        )
                    )

                );

                $help_text = '';

                if ($this->layout()->tariff->get_tariff_product_id() == 1) {
                    $help_text = 'Ihr Anbieterwechsel wird frühestens zu dem von Ihnen genannten Datum durchgeführt. Sollte der gewünschte Wechseltermin nicht realisierbar sein, wird der Wechselprozess automatisch zum nächstmöglichen Termin durchgeführt. Eine eventuelle Zwischenversorgung ist durch Ihren lokalen Grundversorger zu jeder Zeit rechtlich sichergestellt.';
                } else {
                    $help_text = 'Ihr Anbieterwechsel wird frühestens zu dem von Ihnen genannten Datum durchgeführt. Sollte der gewünschte Wechseltermin nicht realisierbar sein, wird der Wechselprozess automatisch zum nächstmöglichen Termin durchgeführt. Eine eventuelle Zwischenversorgung ist durch Ihren lokalen Grundversorger zu jeder Zeit rechtlich sichergestellt.';
                }

                if ($form->get('delivery_date')->getAttribute('type') == 'select') {
                    echo $this->form->render($this->form->generate_select_label_field('delivery_date', 'Belieferung ab', array(), $form->get('delivery_self')->getValue() == 'yes', array('title' => 'Wunschtermin', 'content' => $help_text)));
                } else {
                    echo $this->form->render($this->form->generate_date_field('delivery_date', 'Belieferung ab', array(), $form->get('delivery_self')->getValue() == 'yes', array('title' => 'Wunschtermin', 'content' => $help_text)));
                }

            }

            if ($this->form->has('company_sector')) {
                $star = ($company_sector_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_sector', 'Branche ' . $star, array(), true, array('title' => 'Branche', 'content' => 'Bitte geben Sie Ihre Branche an.')));
            }

            if ($this->form->has('company_function')) {
                $star = ($company_function_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_function', 'Ihre Position ' . $star, array(), true, array('title' => 'Position', 'content' => 'Bitte geben Sie Ihre Position bzw. Ihre Funktion im Unternehmen an.')));
            }

            if ($this->form->has('company_type')) {
                $star = ($company_type_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('company_type', 'Rechtsform ' . $star, array(), true, array('title' => 'Rechtsform', 'content' => 'Bitte wählen Sie Ihre Rechtsform aus.')));
            }

            if ($this->form->has('legalform')) {
                $star = ($legalform_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('legalform', 'Rechtsform ' . $star, array(), true, array('title' => 'Rechtsform', 'content' => 'Rechtsform Ihres Unternehmens')));
            }

            if ($this->form->has('section')) {
                $star = ($section_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('section', 'Branche ' . $star, array(), true, array('title' => 'Branche', 'content' => 'Branche Ihres Unternehmens')));
            }

            if ($this->form->has('owner_diff_address')) {
                $star = ($owner_diff_address_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_radio_field('owner_diff_address', 'Abweichende Inhaber-Adresse ' . $star, array(), true, array('title' => 'Abweichende Inhaber-Adresse', 'content' => 'Wählen Sie hier \'ja\', wenn der Inhaber nicht mit dem Antragsteller übereinstimmt')));
            }

            if ($this->form->has('owner_gender')) {
                $star = ($owner_gender_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('owner_gender', 'Anrede ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_firstname')) {
                $star = ($owner_firstname_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_firstname', 'Vorname ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_lastname')) {
                $star = ($owner_lastname_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_lastname', 'Nachname ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_street')) {
                $star = ($owner_street_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_street', 'Straße ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_streetnumber')) {
                $star = ($owner_streetnumber_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_streetnumber', 'Hausnr. ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_zipcode')) {
                $star = ($owner_zipcode_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_zipcode', 'PLZ ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_city')) {
                $star = ($owner_city_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('owner_city', 'Ort ' . $star, array(), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('owner_birthdate')) {

                $month = date("m");
                $day = date("d");
                $year = date("Y") - 18;
                $maxdate = $day.'.'.$month.'.'.$year;

                $star = ($owner_birthdate_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('owner_birthdate', 'Geburtsdatum ' . $star, array('max' => $maxdate), $this->form->get('owner_diff_address')->getValue() == 'yes'));
            }

            if ($this->form->has('company_register_number')) {
                $star = ($company_register_number_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_register_number', 'Umsatzsteueridentifikationsnummer ' . $star, array(), true, array('title' => 'Umsatzsteueridentifikationsnummer', 'content' => 'Bitte geben Sie Ihre Umsatzsteueridentifikationsnummer an.')));
            }

            if ($this->form->has('company_register_name')) {
                $star = ($company_register_name_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_register_name', 'Handelsregistergericht ' . $star, array(), true, array('title' => 'Handelsregister', 'content' => 'Falls Sie eine Kapitalgesellschaft oder einen Verein vertreten geben Sie bitte hier das zuständige Handelsregister an.')));
            }

            if ($this->form->has('company_tax_number')) {
                $star = ($company_tax_number_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_tax_number', 'Steuernummer ' . $star, array(), true, array('title' => 'Steuernummer', 'content' => 'Bitte geben Sie, falls vorhanden, Ihre Steuernummer an. Eine Angabe entweder der Steuernummer oder der Ust.-IdNr. ist erforderlich.')));
            }

            if ($this->form->has('company_vat_number')) {
                $star = ($company_vat_number_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('company_vat_number', 'Ust.-IdNr. ' . $star, array(), true, array('title' => 'Ust.-IdNr.', 'content' => 'Bitte geben Sie, falls vorhanden, Ihre Ust.-IdNr. an. Eine Angabe entweder der Steuernummer oder der Ust.-IdNr. ist erforderlich.')));
            }

            if ($this->form->has('formation')) {
                $star = ($formation_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('formation', 'Gründungsdatum ' . $star, arraY(), true, array('title' => 'Gründungsdatum', 'content' => 'Wann wurde Ihr Unternehmen gegründet?')));
            }

            if ($this->form->has('contact_gender')) {
                $star = ($contact_gender_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_field('contact_gender', 'Anrede des Ansprechpartners ' . $star, array(), true, array('title' => 'Anrede des Ansprechpartners', 'content' => 'Wie sollen wir den Ansprechpartner in Ihrem Unternehmen ansprechen?')));
            }

            if ($this->form->has('company_contact_type')) {
                $star = ($company_contact_type_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_field('company_contact_type', 'Ansprechpartner ' . $star, array(), true, array('title' => 'Ansprechpartner', 'content' => 'Bitte wählen Sie den Ansprechpartner aus.')));
            }

            if ($this->form->has('consumption_from')) {
                $star = ($consumption_from_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('consumption_from', 'Zeitraum des Verbrauches von ' . $star));
            }

            if ($this->form->has('consumption_to')) {
                $star = ($consumption_to_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('consumption_to', 'Zeitraum des Verbrauches bis ' . $star));
            }

            if ($this->form->has('contract_term_cancelation')) {

                echo $this->form->render(

                    $this->form->generate_select_label_field(
                        'contract_term_cancelation',
                        'Kündigungsfrist',
                        array(),
                        true,
                        array(
                            'title' => 'Kündigungsfrist',
                            'content' => 'Die Kündigungsfrist Ihres aktuellen Vertrags. Ist Ihnen diese nicht bekannt wählen Sie <i>unbekannt</i>.'
                        )
                    )

                );

            }

            if ($this->form->has('movein_period')) {
                $star = ($movein_period_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('movein_period', 'Wann findet/fand der Einzug statt ' . $star));
            }

            if ($this->form->has('username')) {
                $star = ($username_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('username', 'Benutzername ' . $star, array(), true, array('title' => 'Benutzername', 'content' => 'Bitte geben Sie hier Ihren gewünschten Benutzernamen ein. Sie benötigen Ihren Benutzernamen zur persönlichen Anmeldung im Stadtwerke Duisburg R(H)EINPOWER Online-Servcie-Center (dort können Sie bspw. Ihre Kundendaten einsehen und bearbeiten, Ihren Zählerstand übermitteln etc.). Der Benutzername darf eine Länge von mindestens 5 und höchstens 10 Zeichen haben. Erlaubte Zeichen sind Großbuchstaben, Ziffern, Unterstriche und Punkte. Es können keine Leerzeichen verwendet werden.')));
            }

            if ($this->form->has('password_question')) {
                $star = ($password_question_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('password_question', 'Ihre Sicherheits-Frage ' . $star, array(), true, array('title' => 'Sicherheits-Frage', 'content' => 'Bitte wählen Sie eine Sicherheitsfrage aus und geben die entsprechende Antwort ein. Sie benötigen die Antwort zur Aktivierung Ihres Kundenprofils bei 123 energie.')));
            }

            if ($this->form->has('password_answer')) {
                $star = ($password_answer_mandatory) ? ' *' : '';
                $password_answer_text = '';
                $password_answer_help_text = '';
                if ($password_answer_type == 'password_answer_energy2day') {
                    $password_answer_text = 'Persönliches Kennwort für die Kundenbetreuung';
                    $password_answer_help_text = 'Ihr persönliches Kennwort dient zur Identifizierung an der Hotline. So werden die Daten vor unbefugtem Zugriff geschützt.';
                } else {
                    $password_answer_text = 'Antwort auf die Sicherheits-Frage';
                    $password_answer_help_text = 'Bitte wählen Sie eine Sicherheitsfrage aus und geben die entsprechende Antwort ein. Sie benötigen die Antwort zur Aktivierung Ihres Kundenprofils.';
                }
                echo $this->form->render($this->form->generate_text_field('password_answer', $password_answer_text . ' ' . $star, array(), true, array('title' => $password_answer_text, 'content' => $password_answer_help_text)));
            }

            if ($this->form->has('counter_reading')) {
                $star = ($counter_reading_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('counter_reading', 'Zählerstand' . $star, array(), true, array('title' => 'Zählerstand', 'content' => 'Stand des Zählers zur Hauptzeit')));
            }

            if ($this->form->has('counter_date')) {
                $star = ($counter_date_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('counter_date', 'Ablesedatum' . $star, array(), true, array('title' => 'Letzte Ablesung', 'content' => 'Wann wurde der Zählerstand abgelesen?')));
            }

            if ($this->form->has('building')) {
                $star = ($building_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_select_label_field('building', 'Gebäudeart ' . $star, array(), true, array('title' => 'Gebäudeart', 'content' => 'Gebäudeart an der Lieferadresse')));
            }

            if ($this->form->has('usage')) {

                $usage_error = $this->form->get('usage')->getMessages();
                $usage_star = ($usage_mandatory) ? ' *' : '';

                ?>

                <div class="c24-content-row ui-checkbox c24-content-row-info <?php if (!empty($usage_error)) echo 'c24-content-row-error'; ?>" id="usage_container">


                    <div id="c24-content-row-usage" class="c24-clearfix c24-content-row-block">

                        <div class="c24-content-row-info-content">

                            <label for="usage_container" class="c24-block-label-top c24-label">
                                Gasverwendung<?php echo $usage_star; ?> (Mehrfachauswahl möglich)
                            </label>

                            <?php
                                if ($this->form->has('usage_heat')) {
                                    $star = ($usage_heat_mandatory) ? ' *' : '';
                                    echo $this->form->render($this->form->generate_checkbox_field('usage_heat', 'Heizen ' . $star, array(), true));
                                }

                                if ($this->form->has('usage_cook')) {
                                    $star = ($usage_cook_mandatory) ? ' *' : '';
                                    echo $this->form->render($this->form->generate_checkbox_field('usage_cook', 'Kochen ' . $star, array(), true));
                                }

                                if ($this->form->has('usage_water')) {
                                    $star = ($usage_water_mandatory) ? ' *' : '';
                                    echo $this->form->render($this->form->generate_checkbox_field('usage_water', 'Warmwasser ' . $star, [], true));
                                }

                            ?>

                        </div>

                        <div class="c24-content-row-info-icon">
                            <div class="c24-info-icon">?</div>
                        </div>

                    </div>

                    <div class="c24-content-row-block-infobox clearfix">
                        <div class="c24-content-row-info-text">
                            <div class="c24-content-row-info-text-content">
                                Wählen Sie hier aus, für was das Gas genutzt werden soll.
                            </div>
                            <div class="c24-info-text-puffer-layer"></div>
                        </div>
                    </div>

                    <div class="c24-content-row-block-errorbox">
                        <?php

                            if (!empty($usage_error)) {
                                echo $usage_error['api'];
                            }

                        ?>
                    </div>

                </div>

                <?php

            }

            if ($this->form->has('customer_card')) {
                $star = ($customer_card_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_radio_field('customer_card', 'Ich möchte eine EnviaM Kundenkarte ' . $star, array(), true, array('title' => 'enviaM CARD', 'content' => 'Mit der kostenlosen enviaM CARD erhalten Sie als enviaM Privatkunde Vergünstigungen und Service-Vorteile bei über 1.000 enviaM CARD-Partnern deutschlandweit. Ob beim Freizeitpark-Besuch, im Museum, bei einer Hotelübernachtung während eines Wochenendausfluges oder beim Umzug - mit der enviaM CARD erhalten Sie und Ihre Familie Preis- und Servicevorteile von zehn, zwanzig und mehr Prozent.')));
            }

            if ($this->form->has('last_bill_start_date')) {
                $star = ($last_bill_start_date_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('last_bill_start_date', 'Beginn der letzten Abrechnungsperiode ' . $star, array(), true, array('title' => 'Abrechnungsperiode', 'content' => 'Bitte geben Sie hier den Beginn der letzten Abrechnungsperiode ein.')));
            }

            if ($this->form->has('last_bill_end_date')) {
                $star = ($last_bill_end_date_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_date_field('last_bill_end_date', 'Ende der letzten Abrechnungsperiode ' . $star, array(), true, array('title' => 'Abrechnungsperiode', 'content' => 'Bitte geben Sie hier das Ende der letzten Abrechnungsperiode ein.')));
            }

            if ($this->form->has('last_bill_consumption')) {
                $star = ($last_bill_consumption_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('last_bill_consumption', 'Verbrauch in der letzten Abrechnungsperiode ' . $star, array(), true, array('title' => 'Verbrauch', 'content' => 'Bitte geben Sie hier den Verbrauch der letzten Abrechnungsperiode ein entsprechend der Angabe in der letzten Jahresabrechnung ein.')));
            }

            if ($this->form->has('consumption_annual_nt')) {
                $star = ($consumption_annual_nt_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('consumption_annual_nt', 'Verbrauch in der Nebenzeit ' . $star, array(), true, array('title' => 'Verbrauch in der Nebenzeit', 'content' => 'Für diesen Vertag ist es wichtig, dass Sie den Verbrauch in der Nebenzeit angeben.')));
            }

            if ($this->form->has('skip_provider_check')) {
                echo $this->form->render($this->form->generate_hidden_field('skip_provider_check'));
            }

            if ($this->form->has('living_area')) {
                $star = ($living_area_mandatory) ? ' *' : '';
                echo $this->form->render($this->form->generate_text_field('living_area', 'Wohnfläche ' . $star, array(), true, array('title' => 'Wohnfläche', 'content' => 'Geben Sie hier die Wohnfläche in Quadratmetern an.')));
            }

        ?>

    </div>

    <div class="c24-form-element-center">
        <input type="submit" value="weiter" class="c24-button-plain-blue full_button">
    </div>

</div>

<?php
    echo $this->form()->closeTag();
?>
<input type="hidden" id="register_container_id" value="<?php echo $register_container_id; ?>" />
<input type="hidden" id="product_id" value="<?php echo $product_id;?>" />
<input type="hidden" id="zipcode" value="<?php echo $zipcode;?>" />
<input type="hidden" id="provider_id" value="<?php echo $provider_id;?>" />
<div id="c24-important-field-info">
    * Pflichtfeld
</div>

<script type="text/javascript">
    
    <?php if (!in_array($this->layout()->tariff->get_provider_id(), [11290, 11129, 11038, 11317, 12127, 12128])): ?>
        var remove_previous_step = true;
    <?php else: ?>
        var remove_previous_step = false;
    <?php endif; ?>

</script>