<?php
    echo $this->form()->openTag($form);
?>

<div class="c24-form-start" id="c24-register-terms">

    <?php if ($cs_code !== NULL): ?>
    <div class="c24-form-element-group c24-register-terms-list">

        <input type="hidden" name="cs_code" value="<?php echo ($cs_code !== NULL) ? $cs_code->get_code() : ''; ?>" />


            <b>Ihr Gutscheincode</b><br /><?php echo $cs_code->get_code(); ?>

    </div>
    <?php endif; ?>

    <div class="c24-form-element-group c24-register-agreement">

        <?php

            if ($this->form->has('household_protection_letter')) {

                $hausehold_protection_text = 'Ja, ich möchte den Zusatzservice (Haushaltsschutzbrief) für 0 € im ersten Versicherungsjahr, anschließend für 5,99 €/Monat mit diesem Kauf abschließen. Ich akzeptiere die <a class="c24-color" target="_blank" href="' . $household_protection_terms_url . '">AVB</a>, die <a href="#" style="text-decoration: none;" class="c24-color c24-overlay-open" for="c24-register-info-household_bank">Einzugsermächtigung</a> und die <a href="#" style="text-decoration: none;" class="c24-color c24-overlay-open" for="c24-register-info-household_revocation" >Widerrufsbelehrung.</a>';

                echo $this->form->render($this->form->generate_checkbox_field('household_protection_letter', $hausehold_protection_text, array(), true, array('title' => 'Haushaltsschutzbrief', 'content' => 'Sie haben die Möglichkeit, einen Energietarif inklusive einem Zusatzservice (Haushaltsschutzbrief) für Ihre Lieferadresse abzuschließen. Dieser Zusatzservice kostet im ersten Versicherungsjahr 0 €, ab dem zweiten Versicherungsjahr 5,99 €/Monat. Der Haushaltsschutzbrief beinhaltet die Kostenübernahme von bis zu 500 €/Notfall (max. 1500 €/Jahr) für z.B. Schlüsseldienst, Rohrreinigungs-, Sanitär- und Elektroinstallateur-Services, Schädlingsbekämpfung, Notfallbetreuung sowie zahlreiche weitere Leistungen.')));

            }

            if ($this->form->has('mailbill')) {

                $mailbill_text = 'Für ' . $mailbill_costs_label . ' möchte ich die Rechnungen per Post bekommen';
                $mailbill_help_text = 'Der von Ihnen gewählte Tarif ist ein Online-Tarif, d.h. dass Sie Ihre Rechnungen in der Regel per E-Mail oder über ein Online-Kundenportal erhalten. Für ' . $mailbill_costs_label . ' können Sie sich Ihre Rechnungen auch postalisch zusenden lassen.';

                echo $this->form->render($this->form->generate_checkbox_field('mailbill', $mailbill_text, array(), true, array('title' => 'Rechnung per Post', 'content' => $mailbill_help_text)));

            }

            if (($this->form->has('household_protection_letter')) || ($this->form->has('mailbill'))) {
                echo '<div class="c24-register-border-top">';
            }

            if ($this->form->has('agb_tariff_read')) {

                $agreement = 'Ich akzeptiere die <a class="c24-color" href="' . $tariff_terms . '" target="_blank">AGB des Versorgers</a>';

                if ($direct_debit != '') {
                    $agreement .= ', die <a href="#directdebit" class="c24-color">Einzugsermächtigung</a>';
                }

                if ($user_credit_check != '') {
                    $agreement .= ', die <a href="#usercreditcheck" class="c24-color">Bonitätsprüfung</a>';
                }

                if ($code_of_conduct != '') {
                    $agreement .= ', die <a href="#codeofconduct" class="c24-color">Hinweis zum Abschluss</a>';
                }

                if ($datasecurity_agreement != '') {
                    $agreement .= ', die <a href="#datasecurity" class="c24-color">Datenschutzerklärung</a>';
                }

                if ($revocation_register != '') {
                    $agreement .= ', die <a href="#revocation" class="c24-color">Widerrufsbelehrung</a>';
                }

                if ($revocation_register_addon != '') {
                    $agreement .= ', die <a href="#providerauthority" class="c24-color">Versorgervollmacht</a>. *';
                    $agreement .= ' und die <a href="#register-addon" class="c24-color">Informationen zur Wertersatzpflicht</a>';
                } else {
                    $agreement .= ' und die <a href="#providerauthority" class="c24-color">Versorgervollmacht</a>. *';
                }

                echo $this->form->render($this->form->generate_checkbox_field('agb_tariff_read', $agreement, array(), true, array('title' => 'Hinweise zum Versorger', 'content' => 'Bitte lesen Sie sich die AGB des Versorgers, die Widerrufsbelehrung sowie die weiteren Bedingungen des Versorgers aufmerksam durch. Bitte bestätigen Sie, dass Sie alle wichtigen Hinweise vor Vertragsabschluss gelesen haben und diese akzeptieren. Mit der Versorgervollmacht beauftragen Sie Ihren neuen Versorger, alle Formalitäten für den Wechsel für Sie durchzuführen.')));

            }

            if ($this->form->has('accept_conditions')) {
                echo $this->form->render($this->form->generate_checkbox_field('accept_conditions', 'Ich akzeptiere die <a class="c24-color" target="_blank" href="' . htmlspecialchars($accept_conditions_terms) . '">Preis- und Lieferbedingungen</a> als wesentlichen Bestandteil dieses Vertrages. *'));
            }


        ?>

        <div class="c24-content-row agb_click_info">
            <div class="c24-checkbox c24-clearfix c24-content-row-block">
                <div class="c24-checkbox-content">
                    Mit Klick auf "weiter zur Zusammenfassung" bestätige ich die Kenntnisnahme der <a href="http://vergleich.check24.de/app/form/agb_energy.html?style=check24-bluegrey&amp;pid=24&amp;tid=CH24_E_Website" target="_blank" class="c24-color">AGB</a> der CHECK24 Vergleichsportal Energie GmbH. Die Leistungen von CHECK24 sind selbstverständlich kostenlos.
                </div>
            </div>
        </div>

        <?php

            $newsletter_text = '70 CHECK24 Punkte (7 € für Sie!)<br/>Um die Vorteile des CHECK24 Punkte Programms (siehe <a href="https://kundenbereich.check24.de/werbeaktionen/check24-punkte/teilnahmebedingungen.html" target="_blank" class="c24-color">Teilnahmebedingungen</a>) nutzen zu können, stimme ich zu, dass die CHECK24 Vergleichsportal GmbH mich über Angebote, Gutscheine und Newsletter per E-Mail und Post zu den <a href="https://www.check24.de/popup/produktuebersicht/" class="c24-color" target="_blank">Produkten der CHECK24 Gruppe</a> informiert.<br />Diese Einwilligung kann ich jederzeit mit Wirkung für die Zukunft per E-Mail an punkte@check24.de widerrufen.</p> ';

            if (($login_type == 'login' && $is_super_account == false) || $login_type == 'register' || ($login_type == 'session' && $is_super_account == false)) {

                echo $this->form->render($this->form->generate_checkbox_field('newsletter', $newsletter_text, array(), true, array('title' => 'newsletter', 'content' => 'Willkommensbonus + Stromabschluss <br /> &nbsp;&nbsp;&nbsp;50 CHECK24 Punkte <br /> + 20 CHECK24 Punkte <br /> = 70 CHECK24 Punkte <br /> (7,- € geschenkt für Sie!) <br /> So wertvoll wie bares Geld: einlösbar ab 200 Punkte = 20,- €')));

            } else {

                if (!$payback_customer && !$is_super_account) {

                    echo $this->form->render($this->form->generate_checkbox_field('newsletter', 'Ich möchte gerne regelmäßig einen CHECK24 Newsletter erhalten.'));

                }

            }

            if (($this->form->has('household_protection_letter')) || ($this->form->has('mailbill'))) {
                echo '</div>';
            }

        ?>

    </div>

    <div class="c24-form-element-center">
        <input type="submit" value="weiter zur Zusammenfassung" class="c24-button-plain-blue full_button">
    </div>

    <div class="c24-register-terms-list">

        <?php

            if ($onlinesubscription != '') {

                echo '<div class="c24-register-terms-item" id="providerauthority">';
                echo '<strong class="c24-register-items-headline">Versorgervollmacht</strong>';
                echo '<span>' . nl2br($onlinesubscription) . '</span>';
                echo '</div>';

            }

            if ($revocation_register != '') {

                echo '<div class="c24-register-terms-item" id="revocation">';
                echo '<strong class="c24-register-items-headline">Widerrufsbelehrung</strong>';
                echo '<span>' . nl2br($revocation_register) . '</span>';
                echo '</div>';

                if ($revocation_register_addon != '') {

                    echo '<div class="c24-register-terms-item" id="register-addon">';
                    echo '<strong class="c24-register-items-headline">Informationen zur Wertersatzpflicht</strong>';
                    echo '<span>' . nl2br($revocation_register_addon) . '</span>';
                    echo '</div>';

                }

            }

            if ($direct_debit != '') {

                echo '<div class="c24-register-terms-item" id="directdebit">';
                echo '<strong class="c24-register-items-headline">Einzugsermächtigung</strong>';
                echo '<span>' . nl2br($direct_debit) . '</span>';
                echo '</div>';

            }

            if ($user_credit_check != '') {

                echo '<div class="c24-register-terms-item" id="usercreditcheck">';
                echo '<strong class="c24-register-items-headline">Bonitätsprüfung</strong>';
                echo '<span>' . nl2br($user_credit_check) . '</span>';
                echo '</div>';

            }

            if ($datasecurity_agreement != '') {

                echo '<div class="c24-register-terms-item" id="datasecurity">';
                echo '<strong class="c24-register-items-headline">Datenschutzerklärung</strong>';
                echo '<span>' . nl2br($datasecurity_agreement) . '</span>';
                echo '</div>';

            }

            if ($code_of_conduct != '') {

                echo '<div class="c24-register-terms-item" id="codeofconduct">';
                echo '<strong class="c24-register-items-headline">Hinweis zum Abschluss</strong>';
                echo '<span>' . nl2br($code_of_conduct) . '</span>';
                echo '<span>Mehr Informationen unter: <a href="' . htmlspecialchars($code_of_conduct_link) . '" target="_blank" class="c24-color">' . htmlspecialchars($code_of_conduct_link) . '</a></span>';
                echo '</div>';

            }

         ?>

    </div>

    <div class="c24-form-element-group c24-register-agreement">

        <?php

            if ($this->form->has('household_protection_letter')) {

                $hausehold_protection_text = 'Ja, ich möchte den Zusatzservice (Haushaltsschutzbrief) für 0 € im ersten Versicherungsjahr, anschließend für 5,99 €/Monat mit diesem Kauf abschließen. Ich akzeptiere die <a class="c24-color" target="_blank" href="' . $household_protection_terms_url . '">AVB</a>, die <a href="#" style="text-decoration: none;" class="c24-color c24-overlay-open" for="c24-register-info-household_bank">Einzugsermächtigung</a> und die <a href="#" style="text-decoration: none;" class="c24-color c24-overlay-open" for="c24-register-info-household_revocation" >Widerrufsbelehrung.</a>';

                echo $this->form->render($this->form->generate_checkbox_field('household_protection_letter_down', $hausehold_protection_text, array(), true, array('title' => 'Haushaltsschutzbrief', 'content' => 'Sie haben die Möglichkeit einen Energietarif inklusive einem Zusatzservice (Haushaltsschutzbrief) abzuschließen. Dieser Zusatzservice kostet im ersten Versicherungsjahr 0 €, ab dem zweiten Versicherungsjahr 5,99 €/Monat. Der Haushaltsschutzbrief beinhaltet die Kostenübernahme von bis zu 500 €/Notfall (max. 1500 €/Jahr) für z.B. Schlüsseldienst, Rohrreinigungs-, Sanitär- und Elektroinstallateur-Services, Schädlingsbekämpfung, Notfallbetreuung sowie zahlreiche weitere Leistungen.')));

            }

            if ($this->form->has('mailbill_down')) {

                $mailbill_text = 'Für ' . $mailbill_costs_label . ' möchte ich die Rechnungen per Post bekommen';
                $mailbill_help_text = 'Der von Ihnen gewählte Tarif ist ein Online-Tarif, d.h. dass Sie Ihre Rechnungen in der Regel per E-Mail oder über ein Online-Kundenportal erhalten. Für ' . $mailbill_costs_label . ' können Sie sich Ihre Rechnungen auch postalisch zusenden lassen.';

                echo $this->form->render($this->form->generate_checkbox_field('mailbill_down', $mailbill_text, array(), true, array('title' => 'Rechnung per Post', 'content' => $mailbill_help_text)));

            }

            if (($this->form->has('household_protection_letter')) || ($this->form->has('mailbill'))) {
                echo '<div class="c24-register-border-top">';
            }

            if ($this->form->has('agb_tariff_read_down')) {

                $agreement = 'Ich akzeptiere die <a class="c24-color" href="' . $tariff_terms . '" target="_blank">AGB des Versorgers</a>';

                if ($direct_debit != '') {
                    $agreement .= ', die <a href="#directdebit" class="c24-color">Einzugsermächtigung</a>';
                }

                if ($user_credit_check != '') {
                    $agreement .= ', die <a href="#usercreditcheck" class="c24-color">Bonitätsprüfung</a>';
                }

                if ($code_of_conduct != '') {
                    $agreement .= ', die <a href="#codeofconduct" class="c24-color">Hinweis zum Abschluss</a>';
                }

                if ($datasecurity_agreement != '') {
                    $agreement .= ', die <a href="#datasecurity" class="c24-color">Datenschutzerklärung</a>';
                }

                if ($revocation_register != '') {
                    $agreement .= ', die <a href="#revocation" class="c24-color">Widerrufsbelehrung</a>';
                }

                if ($revocation_register_addon != '') {
                    $agreement .= ', die <a href="#revocation" class="c24-color">Versorgervollmacht</a>. *';
                    $agreement .= ' und die <a href="#register-addon" class="c24-color">Informationen zur Wertersatzpflicht</a>';
                } else {
                    $agreement .= ' und die <a href="#providerauthority" class="c24-color">Versorgervollmacht</a>. *';
                }

                echo $this->form->render($this->form->generate_checkbox_field('agb_tariff_read_down', $agreement, array(), true, array('title' => 'Hinweise zum Versorger', 'content' => 'Bitte lesen Sie sich die AGB des Versorgers, die Widerrufsbelehrung sowie die weiteren Bedingungen des Versorgers aufmerksam durch. Bitte bestätigen Sie, dass Sie alle wichtigen Hinweise vor Vertragsabschluss gelesen haben und diese akzeptieren. Mit der Versorgervollmacht beauftragen Sie Ihren neuen Versorger, alle Formalitäten für den Wechsel für Sie durchzuführen.')));

            }

            if ($this->form->has('accept_conditions_down')) {
                echo $this->form->render($this->form->generate_checkbox_field('accept_conditions_down', 'Ich akzeptiere die <a class="c24-color" target="_blank" href="' . htmlspecialchars($accept_conditions_terms) . '">Preis- und Lieferbedingungen</a> als wesentlichen Bestandteil dieses Vertrages. *'));
            }

        ?>

        <div class="c24-content-row agb_click_info">
            <div class="c24-checkbox c24-clearfix c24-content-row-block">
                <div class="c24-checkbox-content">
                    Mit Klick auf "weiter zur Zusammenfassung" bestätige ich die Kenntnisnahme der <a href="http://vergleich.check24.de/app/form/agb_energy.html?style=check24-bluegrey&amp;pid=24&amp;tid=CH24_E_Website" target="_blank" class="c24-color">AGB</a> der CHECK24 Vergleichsportal Energie GmbH. Die Leistungen von CHECK24 sind selbstverständlich kostenlos.
                </div>
            </div>
        </div>

        <?php

            if (($login_type == 'login' && $is_super_account == false) || $login_type == 'register' || ($login_type == 'session' && $is_super_account == false)) {

                echo $this->form->render($this->form->generate_checkbox_field('newsletter_down', $newsletter_text, array(), true, array('title' => 'newsletter', 'content' => 'Willkommensbonus + Stromabschluss = 70 CHECK24 Punkte (7,- € geschenkt für Sie!) So wertvoll wie bares Geld: einlösbar ab 200 Punkte = 20,- €')));

            } else {

                if (!$payback_customer && !$is_super_account) {

                    echo $this->form->render($this->form->generate_checkbox_field('newsletter_down', 'Ich möchte gerne regelmäßig einen CHECK24 Newsletter erhalten.'));

                }

            }

            if (($this->form->has('household_protection_letter')) || ($this->form->has('mailbill'))) {
                echo '</div>';
            }

        ?>

    </div>

    <div class="c24-form-element-center">
        <input type="submit" value="weiter zur Zusammenfassung" class="c24-button-plain-blue full_button">
    </div>

</div>

<?php
    if ($this->form->has('household_protection_letter')) {

    ?>

        <div id="c24-register-info-household_bank" class="c24-overlay-items">

            <div class="c24-overlay-close">X</div>

            <span class="c24-overlay-headline">Einzugsermächtigung</span>
            <?php echo htmlspecialchars($household_bank_text); ?>


            <ul style="font-size:11px;width:200px;margin:20px auto 20px auto"
            <li><b>Kontonummer:</b> <?php echo $accountnumber; ?></li>
            <li><b>Bankleitzahl:</b> <?php echo $bankcode; ?></li>
            <li><b>Bank:</b> <?php echo $bank; ?></li>
            <li><b>Kontoinhaber:</b> <?php echo $account_owner_firstname . ' ' . $account_owner_lastname; ?></li>
            </ul>
        </div>

        <div id="c24-register-info-household_revocation" class="c24-overlay-items">
            <div class="c24-overlay-close">X</div>

            <span class="c24-overlay-headline">Widerrufsbelehrung Haushaltsschutzbrief</span>
            <?php echo htmlspecialchars($household_revocation_text); ?>


        </div>

    <?php

    }
?>


<?php
    echo $this->form()->closeTag();
?>

<div id="c24-important-field-info">
    * Pflichtfeld
</div>
