<div id="c24-register-converted">

    <div id="c24-register-converted-infos">

        <div id="c24-converted-thx">
            <div id="c24-register-converted-text">
                <span id="c24-converted-thx-title">Vielen Dank</span>
            </div>
        </div>
        <div class="c24-register-thank_info_wrapper">
            <p>Wir haben Ihre Anfrage erhalten. Ihr persönlicher PKV-Experte meldet sich umgehend bei Ihnen.</p>
            <p>Ihre Anfragenummer: <b><?php echo $this->offer_id ?></b></p>
        </div>

        <span id="c24-converted-next-steps-toggle">So geht es weiter</span>

        <ul id="c24-converted-next-steps">

            <li class="clearfix">
                <div class="thx-number-first"></div>
                <div class="text">
                    <h1>Persönliche Beratung</h1>
                    <img src="/massets/images/styleguide/persoenlich-versichern-01.png" class="icons_mail_post">
                    <p>Ihr persönlicher CHECK24 PKV-Experte berät Sie telefonisch.</p>
                </div>


            </li>

            <li class="clearfix">

                <div class="thx-number-second"></div>
                <div class="text">
                    <h1>In Ruhe prüfen</h1>
                    <img src="/massets/images/styleguide/vielen-dank-02.png" class="icons_mail_post">
                    <p>Sie erhalten Ihr persönliches Angebot schriftlich kostenfrei und unverbindlich. Ihr PKV-Experte unterstützt Sie bei allen weiteren Fragen.</p>
                </div>

            </li>

            <li class="clearfix">

                <div class="thx-number-third"></div>
                <div class="text">
                    <h1>Einfach beantragen</h1>
                    <img src="/massets/images/styleguide/so-einfach-versichern-03.png" class="icons_mail_post">
                    <p>Senden Sie uns den ausgefüllten Antrag einfach zurück. Wir kümmern uns um den Rest!</p>
                </div>

            </li>

        </ul>

        <span id="c24-converted-next-steps-toggle">Noch Fragen?</span>

        <div class="content clearfix">
            <p>Sie erreichen unsere PKV-Experten<br/> Mo. bis So. 8:00 - 20:00 Uhr unter <br/><a class="phone_thank" href="tel:089 - 24 24 12 72">089 - 24 24 12 72</a><span class="content-email"> oder per E-Mail an <br/><a href="mailto:pkv@check24.de">pkv@check24.de</a></span></p>
            <p>Bitte nennen Sie dazu Ihre Anfragenummer:&nbsp;<b><?php echo $this->offer_id ?></b></p>
            <p>Die Beratung ist kostenfrei und unverbindlich für Sie.</p>
        </div>
    </div>
</div>
