<section>
    <article>
        <div></div>
        <?php foreach($this->tariffs as $key => $tariff): ?>
            <?php $class = $tariff->get_tariff_version_id().'-'.$tariff->get_tariff_variation_key(); ?>
            <div class="<?php $this->output($class) ?> <?php $this->output(!in_array($class, $this->selected_keys) ? 'hide' : '') ?>">

                <div class="note_tariff">
                    <div class="logo">
                    <?php $this->output('<img src="' . $tariff->get_provider_logo('150') . '" alt="' . $tariff->get_provider_name() . '" />', false); ?>
                    <?php if ($tariff->get_provider_brand() != ''): ?>
                        <?php $this->output('<br />Marke der ' . $this->escape($tariff->get_provider_brand()), false); ?>
                    <?php endif; ?>
                    </div>
                    <div class="name"><b><?php $this->output($tariff->get_provider_name()) ?></b> - <?php $this->output($tariff->get_tariff_name()); ?></div>
                </div>

                <div class="price">
                    <span><?php $this->output(number_format($tariff->get_paymentperiod_size(), 2, ',', '.') . ' €'); ?></span>
                    <span><?php $this->output($tariff->get_paymentperiod_label_adjectiv()); ?></span>
                </div>


                <?php echo $this->point_plan_helper->render('small') ?>
            </div>
        <?php endforeach; ?>
    </article>
</section>