<?php
$tariff_note  = $this->tariff->get_tariff_promotion() == 'yes' ? 'golden' : '';
$grade = $this->tariff->get_data()['tariff']['grade'];
$grade_class = $grade['result'] >= 2.51 ? 'smaller' : ''
?>




<div class="c24-tooltip tariff_grade <?php $this->output($tariff_note == 'golden' ? 'gold' : '') ?> <?php $this->output($tariff_note) ?>" data-direction="down" data-trigger="click">
    <ul>
        <li class="tariff_grade_score"><?php $this->output(number_format($grade['result'], 1, ',', NULL)) ?></li>
        <li class="tariff_grade_label">Tarifnote</li>
        <li class="tariff_grade_score_text small"><?php echo($grade['name']);?></li>
    </ul>

    <div class="c24-tooltip-content">
        <div class="c24-tooltip-arrow"></div>
        <div class="c24-tooltip-close"></div>
        <h3>Berechnung der Tarifnote <?php $this->output(number_format($grade['result'], 1, ',', NULL)); ?> (<?php $this->output($grade['name']); ?>)</h3>
        <p>Der Tarif erreicht die Gesamtpunktzahl <?php $this->output($grade['total_points']) ?> von <?php $this->output($grade['max_points']) ?></p>
        <div class="tariff_grade_details">
            <div class="arrow_down"></div>
            <ul>
                <?php foreach($grade['feature_details'] as $key => $feature): ?>
                <?php $header = ($grade['feature_details'][$key]['code'] === 'insurer_financial_stability' ? 'Versicherer' : ($grade['feature_details'][$key]['code'] === 'insurer_financial_stability' ? 'Leistungen' : '')); ?>
                    <li class="row">
                        <?php if(!empty($header)): ?>
                            <h4><?php $this->output($header); ?></h4>
                        <?php endif; ?>
                        <ul>
                        <?php if($grade['feature_details'][$key]['code'] === 'dynamic'): ?>
                            <li class="column1">Zusatzleistungen</li>
                            <li class="column2">&nbsp;</li>
                            <li class="column3">&nbsp;</li>
                            <li class="column4">&nbsp;</li>
                            <li class="column5">&nbsp;</li>
                        <?php endif; ?>

                            <li class="column1"><?php $this->output($grade['feature_details'][$key]['name']) ?></li>
                            <?php if($grade['feature_details'][$key]['icon']): ?>
                            <li class="column2"><div class="checkmark <?php $this->output($grade['feature_details'][$key]['icon']) ?>_checkmark_small">&nbsp;</div></li>
                            <?php else: ?>
                            <li class="column2"><?php $this->output($grade['feature_details'][$key]['txt']) ?></li>
                            <?php endif; ?>
                            <li class="column3"><?php $this->output($grade['feature_details'][$key]['points']) ?></li>
                            <li class="column4">von</li>
                            <li class="column5"><?php $this->output($grade['feature_details'][$key]['max_points']) ?></li>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="note_legend">
            <div>
                <div class="checkmark green_checkmark_small"><span>enthalten</span></div>
                <div class="checkmark red_checkmark_small"><span>nicht enthalten</span></div>
            </div>
        </div>
    </div>
</div>

