<section class="ribbons">
    <article>
        <div></div>
        <?php foreach($this->tariffs as $key => $tariff): ?>
        <?php $class = $tariff->get_tariff_version_id().'-'.$tariff->get_tariff_variation_key(); ?>




            <div class="<?php $this->output($class) ?> <?php $this->output(!in_array($class, $this->selected_keys) ? 'hide' : '') ?>">
        <?php if ($tariff->has_special_action_running()): ?>

        <?php
            $valid_to_date = date('d.m', strtotime($tariff->get_special_action()['valid_to']));
            $valid_to_date_full = date('d.m.Y', strtotime($tariff->get_special_action()['valid_to']));;
            $free_months = $tariff->get_special_action()['max_free_months'];
            $max_voucher_value = $tariff->get_special_action()['max_voucher_value'];
            $action_text_how_many_free = $free_months . ' ' . (($free_months) > 1 ? 'Monate' : 'Monat') . ' gratis';
            $action_grey_label = '(nur bis ' . $valid_to_date . ')';
        ?>
            <div class="c24-compare-action-ribbon-container">
                <div class="action_ribbon c24-tooltip" data-direction="down_right_arrow" data-trigger="click" >
                    <p class="title"><?php $this->output($action_text_how_many_free) ?> <small><?php $this->output($action_grey_label) ?></small></p>

                    <div class="info_circle"></div>
                        <div class="c24-tooltip-content">
                            <div class="c24-tooltip-arrow up down"></div>
                            <div class="c24-tooltip-close"></div>
                            <h3>Bis zum <?php $this->output($valid_to_date) ?> – exklusiv nur bei CHECK24: <?php $this->output($action_text_how_many_free) ?></h3>
                            <b>Hinweis zur Auszahlung:</b><br />
                            <ul class="c24-list">
                                <li>Die Versicherung wird Ihnen den Beitrag normal abbuchen</li>
                                <li>Sie erhalten den Gegenwert der <br>„<?php $this->output($action_text_how_many_free) ?>“ Aktion als Cashback auf
                                    die im Antrag angegebene Kontoverbindung direkt von CHECK24 gutgeschrieben
                                    (ca. 6 Wochen nach Zustandekommen des Vertrags), jedoch maximal <?php $this->output($max_voucher_value) ?> € pro Vertrag</li>
                            </ul>
                            <b>Wichtige Bedingungen für die Auszahlung:</b><br />
                            <ul class="c24-list">
                                <li>Der Antrag muss bei CHECK24 bis zum <?php $this->output($valid_to_date_full) ?> eingehen</li>
                                <li>Der Versicherungsvertrag muss policiert sein und darf nicht in der
                                    <br>14-tägigen Widerrufsfrist widerrufen werden</li>
                            </ul>
                        </div>
                </div>
            </div>

            <?php elseif ($tariff->get_tariff_promotion() === 'yes'): ?>

                <?php
                    $tariff_promotion_title = $tariff->get_tariff_promotion() ? $tariff->get_tariff_promotion_title() : '';
                    $tariff_promotion_text  = $tariff->get_tariff_tips_as_string() ? $tariff->get_tariff_tips_as_string() : '';
                ?>
                <div class="c24-compare-action-ribbon-container">
                    <div class="promo_ribbon c24-tooltip" data-direction="down_right_arrow" data-trigger="click">
                        <p class="title"><?php $this->output($tariff_promotion_title, false); ?></p>
                        <?php if($tariff_promotion_text): ?>
                        <div class="info_circle"></div>
                        <div class="c24-tooltip-content">
                            <div class="c24-tooltip-arrow up down"></div>
                            <div class="c24-tooltip-close"></div>
                            <?php $this->output($tariff_promotion_text, false); ?>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
    </article>
</section>