<!-- BEGIN WITH COMPARISON -->
<div id="comparison">
    <header>
        <?php $this->output($this->special_action_ribbon()->render_container(), false); ?>
        <?php $this->output($this->helper->compare_change($this->comparison), false); ?>
        <?php $this->output($this->helper->compare_exclusive($this->comparison), false); ?>
        <?php $this->output($this->helper->compare_header($this->comparison, $this->point_plan_helper), false); ?>
        <?php $this->output($this->helper->compare_buttons($this->comparison), false); ?>
    </header>

    <?php foreach($this->sections as $title => $section): ?>
        <section class="open">
            <?php if($title !== ''): ?>
            <header>
                <div class="switch"></div>
                <h3><?php $this->output($title); ?></h3>
            </header>
            <?php endif; ?>

            <?php if(isset($section['description'])): ?>
                <p><?php $this->output($section['description']) ?></p>
            <?php endif; ?>

            <?php foreach($section as $area): if(!is_array($area)) continue; ?>
                <article><?php $this->output($this->helper->compare_section($area, $this->comparison), false); ?></article>
            <?php endforeach; ?>
        </section>
    <?php endforeach; ?>

    <?php $this->output($this->helper->compare_buttons($this->comparison), false); ?>

    <footer class="clearfix">
        <div>
            <div class="icon OK">= <b>enthalten</b></div>
            <div class="icon NotOK">= <b>nicht enthalten</b></div>
        </div>
    </footer>

    <!-- tariff change popup -->
    <div class="tariff_change_bg">
        <div class="tariff_change_box">
            <header>
                <h3>Bitte wählen Sie einen Tarif</h3>
                <div class="tariff_change_close_button"></div>
            </header>

            <input type="hidden" id="tariff_column" value="">
            <input type="hidden" id="tariff_1" value="<?php $this->output($this->selected_keys[0])?>">
            <input type="hidden" id="tariff_2" value="<?php $this->output($this->selected_keys_count > 1 ? $this->selected_keys[1] : '')?>">
            <input type="hidden" id="tariff_3" value="<?php $this->output($this->selected_keys_count > 2 ? $this->selected_keys[2] : '')?>">
            <input type="hidden" value="<?php $this->output($this->selected_keys_count > 2 ? $this->selected_keys[2] : '')?>" id="tariff_column_3">

            <div class="tariff_list clearfix">
                <?php foreach($this->tariffs as $tariff): ?>
                    <?php $class = $tariff->get_tariff_version_id() . '-' . $tariff->get_tariff_variation_key(); ?>
                    <?php $features = $tariff->get_tariff_feature(); ?>

                    <div data-id="<?php $this->output($class) ?>" class="tariff <?php $this->output(in_array($class, $this->selected_keys) ? 'tariff_checked' : 'tariff_click') ?> clearfix">
                        <div class="price">
                            <span><?php $this->output(number_format($tariff->get_paymentperiod_size(), 2, ',', '.') . ' €'); ?></span>
                            <span><?php $this->output($tariff->get_paymentperiod_label_adjectiv()); ?></span>
                        </div>
                        <div class="logo">
                            <?php $this->output('<img src="' . $tariff->get_provider_logo('115') . '" alt="' . $tariff->get_provider_name() . '" />', false);  ?>
                            <br /><b><?php $this->output($tariff->get_provider_name()) ?></b><br /><?php $this->output($tariff->get_tariff_name()); ?>
                        </div>
                        <div class="note"><?php $this->output($this->helper->compare_note($tariff), false); ?></div>
                        <div class="features"><ul class="tariff_features_list">
                            <?php foreach ($features AS $bullet => $value): ?>
                                <li class="<?php $this->output($value['class']) ?>">
                                    <div class="c24-tooltip" data-direction="up" data-trigger="mouseover">
                                        <?php $this->output($value['header'], false) ?>
                                        <div class="c24-tooltip-content">
                                            <div class="c24-tooltip-arrow"></div>
                                            <div class="c24-tooltip-close"></div>
                                            <h3><?php $this->output($value['tooltip_header'], false) ?></h3>
                                            <?php $this->output($value['tooltip_content'], false) ?>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </div>
                        <div class="arrow"></div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript">
/* <![CDATA[ */
    var comparison_base_link  = '<?php $this->output($this->compare_link) ?>';
    var comparison_pager_keys = ['<?php $this->output(implode("','", $this->pager_keys)) ?>'];
/* ]]> */
</script>

<?php
$this->output($this->generaltracking_pixel, false);
$this->output($this->generaltracking_pixel2, false);
?>
<!-- END WITH COMPARISON -->
