<section class="buttons">
  <article>
    <div class="back_button">
    <?php
    $this->output(
        $this->helper->generate_button_link(
            $this->calculationparameter->get_partner_id(),
            $this->calculationparameter->get_tracking_id(),
            'back',
            '« zurück zur Ergebnisseite',
            $this->back_link,
            '_self'
        ),
        false
    );
    ?>
    </div>
<?php foreach($this->tariffs as $key => $tariff): ?>
<?php $class = $tariff->get_tariff_version_id().'-'.$tariff->get_tariff_variation_key(); ?>
    <div class="<?php $this->output($class) ?> <?php $this->output(!in_array($class, $this->selected_keys) ? 'hide' : '') ?>">
        <?php
        if ($tariff->get_subscription_possible() == 'yes'):

            $this->output('<div id="pkv_loader_spinner"></div>', false);
            $this->output(
                $this->helper->generate_button_link(
                    $this->calculationparameter->get_partner_id(),
                    $this->calculationparameter->get_tracking_id(),
                    'signup',
                    'Angebot anfordern &raquo;',
                    $tariff->subscription_url,
                    '_self',
                    NULL
                ),
                false
            );

        endif;
        ?>
    </div>
<?php endforeach; ?>
  </article>
</section>