<div class="<?php $this->output($this->css_class, false) ?> c24-tooltip" data-direction="left" data-trigger="mouseover">
    <a href="<?php $this->output($this->subscription_url, false); ?>" class="c24-button offer">Angebot anfordern »</a>

    <div class="c24-tooltip-content">
        <div class="c24-tooltip-arrow"></div>
        <div class="c24-tooltip-close"></div>

        <h1 class="price">
            nur <?php $this->output($this->daily_price[0],false) ?>,<?php $this->output($this->daily_price[1],false) ?> € am Tag
        </h1>
        <ul class="check c24-list">
            <?php  foreach($this->tooltip_text as $line): ?>
                <li><?php $this->output($line, false) ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

