<?php $special_action = $this->special_action; ?>

<?php if($special_action->is_active()): ?>
    <div class="banderole ">
        <?php echo $special_action->free_months();?> Monate gratis &mdash; Exklusiv
        nur bei CHECK24 bis <?php echo $special_action->valid_until()->format('d.m.') ?>*

        <div class=" c24-tooltip" data-direction="down" data-trigger="click">
            <div class="info_circle"></div>
            <div class="c24-tooltip-content">
                <div class="c24-tooltip-arrow up down"></div>
                <div class="c24-tooltip-close"></div>
                <h3>Bis zum <?php echo $special_action->valid_until()->format('d.m.') ?> &mdash; exklusiv nur bei CHECK24:
                    <?php echo $special_action->free_months();?> Monate gratis
                </h3>
                <b>Hinweis zur Auszahlung:</b><br />
                <ul class="c24-list">
                    <li>Die Versicherung wird Ihnen den Beitrag normal abbuchen</li>
                    <li>Sie erhalten den Gegenwert der <br>„<?php echo $special_action->free_months();?> Monate gratis“ Aktion als Cashback auf
                        die im Antrag angegebene Kontoverbindung direkt von CHECK24 gutgeschrieben
                        (ca. 6 Wochen nach Zustandekommen des Vertrags), jedoch maximal <?php echo $special_action->max_voucher_value() ?> € pro Vertrag</li>
                </ul>
                <b>Wichtige Bedingungen für die Auszahlung:</b><br />
                <ul class="c24-list">
                    <li>Der Antrag muss bei CHECK24 bis zum  <?php echo $special_action->valid_until()->format('d.m.') ?> eingehen</li>
                    <li>Der Versicherungsvertrag muss policiert sein und darf nicht in der
                        <br>14-tägigen Widerrufsfrist widerrufen werden</li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>