<div class="c24-container-12">
    <a data-fancybox class="tariffIndex-link" href="#tariffIndex">
        Teilnehmende Versicherungen
    </a>


    <div id="tariffIndex" class="tariffIndex">
        <h3>Risikolebensversicherung</h3>
        <p>Bei CHECK24 vergleichen Sie <?php echo count($this->tariffs) ?> Basistarife für eine Risikolebensversicherung.*
            <br />
            (Stand: <?php echo date('d.m.Y');?>)
        </p>

        <table class="tariffIndex-list">
            <thead>
            <tr>
                <td>Versicherer</td>
                <td>Tarif</td>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->tariffs as $tariff): ?>
                <tr>
                    <td><?php echo $tariff['provider_name'] ?></td>
                    <td><?php echo $tariff['tariff_name'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>

        <p>
            * Aufgrund laufender Updates einzelner Tarife, technischer Probleme oder eingeschränkter Verfügbarkeiten
            kann es vorkommen, dass einzelne Versicherer oder Tarife kurzzeitig nicht berechnet oder angezeigt werden können.
        </p>

        <p>
            Eine Auswahl von im Moment nicht in unserem Vergleich enthaltenen Versicherungsunternehmen finden
            Sie hier: AachenMünchener, Allianz, AXA, CosmosDirekt, DEVK Allgemeine, HUK-Coburg, R+V, WGV, Württembergische
        </p>

        <p>
            Kooperationen von Versicherungen werden ggf. zusammengefasst, sofern der Deckungsträger identisch ist.
        </p>
    </div>
</div>
