<style>
    .c24-error-container {
        text-align: center;
    }

    .c24-error-container h2 {
        font-size: 18px;
        font-weight: bold;
    }

    .c24-error-container p {
        font-size: 14px;
        line-height: 25px;
        padding: 10px;
    }
</style>
<br/><br/>
<div class="c24-error-container">
    <h2>404: Es ist leider ein Fehler aufgetreten!</h2>
    <br>
    <p>
        Der Webmaster wurde benachrichtigt und der Fehler wird umgehend behoben.
    </p>
    <br><br>
    <a href="/pkv/" class="c24-button-plain-blue full_button">Zum Vergleich</a><br><br>
</div>
