<?php
namespace Common\Request;

use Common\Calculation\Model as CalculationModel;
use GuzzleHttp\Psr7;
use shared\classes\calculation\client\response;
use Zend\Hydrator\ClassMethods;
use Zend\Json;

/**
 * Trait with mocks for application service
 *
 * @author  Robert Eichholtz <robert.eichholtz@check24.de>
 * @package Common\Request
 */
trait CalculationMockTrait
{
    /**
     * @param CalculationModel\Parameter\User     $userParameter
     * @param CalculationModel\Parameter\Internal $internalParameter
     *
     * @return array
     */
    protected function getGuzzleCalculationRequestValueMap(CalculationModel\Parameter\User $userParameter, CalculationModel\Parameter\Internal $internalParameter)
    {
        /** @var ClassMethods $hydrator */
        $hydrator = $this->getApplicationServiceLocator()->get('HydratorManager')->get('ClassMethods');

        $parameters = array_merge(
            $hydrator->extract($userParameter),
            $hydrator->extract($internalParameter)
        );

        $mockData = [
            'parameter'    =>
                [
                    'id'                           => $userParameter->getCalculationparameterId() ? $userParameter->getCalculationparameterId() : '5c078fae67bf03fa1a69857151cb11c0',
                    'product_id'                   => PRODUCT_GKV,
                    'partner_id'                   => PARTNER_GKV,
                    'tracking_id'                  => 'checkvers',
                    'tracking_id2'                 => '',
                    'tracking_id3'                 => '',
                    'tracking_id4'                 => '',
                    'mode_id'                      => '',
                    'keep'                         => 'no',
                    'timepoint'                    => '2016-06-22 12:36:36',
                    'remote_address'               => $internalParameter->getRemoteAddress() ? $internalParameter->getRemoteAddress() : '172.28.128.1',
                    'style'                        => 'check24-bluegrey',
                    'c24logincsplan_id'            => null,
                    'c24loginpointplan_id'         => null,
                    'occupation_group'             => 'employee',
                    'current_insurance_type'       => 'by_law',
                    'zipcode'                      => $userParameter->getZipcode() ? $userParameter->getZipcode() : '22177',
                    'salary'                       => $userParameter->getSalary() ? $userParameter->getSalary() : 60000,
                    'federal_state'                => 'Hamburg',
                    'service_phone'                => null,
                    'schedule_mediation'           => null,
                    'doctor_search_portal'         => null,
                    'online_patients_receipt'      => null,
                    'homeopathy'                   => null,
                    'osteopathy'                   => null,
                    'alternative_cancer_therapy'   => null,
                    'professional_tooth_cleaning'  => null,
                    'reduced_dental_prosthesis'    => null,
                    'bonus_program'                => null,
                    'retention_program'            => null,
                    'premium_refund'               => null,
                    'additional_nursing_home_care' => null,
                    'vaccinations'                 => null,
                    'free_choice_hospital'         => null,
                    'additional_checkups_adult'    => null,
                    'additional_household_help'    => null,
                    'current_insurer'              => null,
                    'maxtariffs'                   => 0,
                    'provider_id'                  => 0,
                    'company_id'                   => 0,
                ],
            'apiparameter' =>
                [
                    'product_id'                   => PRODUCT_GKV,
                    'update_parameters'            => $internalParameter->getUpdateParameters(),
                    'calculationparameter_id'      => $userParameter->getCalculationparameterId(),
                    'page'                         => 1,
                    'pagesize'                     => 20,
                    'sortfield'                    => $userParameter->getSortfield(),
                    'sortorder'                    => $userParameter->getSortorder(),
                    'debug'                        => 'no',
                    'caching'                      => 'yes',
                    'stats'                        => 'no',
                    'tariffversion_ids'            => null,
                    'tariffversion_variation_keys' => null,
                    'jsonp_callback'               => '',
                    'ignore_filter'                => 'no',
                    'protocol'                     => 'https',
                    'force_current_timepoint'      => 'no',
                    'show_invisible_tariffs'       => 'no',
                    'calculationparameter_save'    => 'yes',
                    'forecast'                     =>
                        [
                        ],
                ],
            'paging'       =>
                [
                    'resultsize'  => 36,
                    'currentpage' => 1,
                    'totalpages'  => 2,
                    'pagesize'    => 20,
                ],
            'result'       =>
                [
                    '11-base' =>
                        [
                            'result'       =>
                                [
                                    'position' => 33,
                                ],
                            'provider'     =>
                                [
                                    'id'                         => 9,
                                    'name'                       => 'AOK Rheinland Hamburg',
                                    'comparename'                => null,
                                    'version_id'                 => 129,
                                    'brand'                      => '',
                                    'brand_provider_id'          => null,
                                    'health_insurance_search_id' => 1,
                                    'company'                    => 'AOK Rheinland Hamburg',
                                    'description'                => '',
                                    'logo'                       => '/filestore/provider_logo/72a88558a7f6c911b2e34a1086e2af1b.svg',
                                    'logo2'                      => '',
                                    'logo_comparison'            => '',
                                    'result_grouping'            => '',
                                    'company_id'                 => 9,
                                    'contact'                    =>
                                        [
                                            'phone'      => '089 2000471403',
                                            'phone_info' => '',
                                            'email'      => '',
                                        ],
                                    'address'                    =>
                                        [
                                            'company' => 'AOK Rheinland Hamburg',
                                            'street'  => 'Kasernenstr. 61',
                                            'zipcode' => '40213',
                                            'city'    => 'Düsseldorf',
                                        ],
                                    'customer_satisfaction'      => 'no',
                                    'auto_tariff_selection'      => 'no',
                                    'efeedback_ids'              => null,
                                    'efeedback_review_id'        => 0,
                                    'creditor_identifier'        => 'DE05ZZZ00000018503',
                                    'sepa_text'                  => '',
                                ],
                            'tariff'       =>
                                [
                                    'id'                         => 11,
                                    'product_id'                 => PRODUCT_GKV,
                                    'version_id'                 => 11,
                                    'variation_key'              => 'base',
                                    'name'                       => 'AOK Rheinland/Hamburg',
                                    'name_pdf'                   => 'AOK Rheinland/Hamburg',
                                    'validfrom'                  => '',
                                    'tips'                       => null,
                                    'promotion'                  => 'no',
                                    'promotion_title'            => '',
                                    'promotion_position'         => null,
                                    'promotion_bin'              => null,
                                    'hide_rule'                  => '',
                                    'promotion_tariff_id'        => 0,
                                    'description'                => 'Die Gesundheitskasse',
                                    'code'                       => '',
                                    'actioncode'                 => '',
                                    'communication'              => 'normal',
                                    'attachments'                =>
                                        [
                                            'appform'           => null,
                                            'encrypted_appform' => null,
                                        ],
                                    'grade'                      =>
                                        [
                                            'max_points'      => 0,
                                            'total_points'    => 0,
                                            'result'          => 1,
                                            'name'            => 'sehr gut',
                                            'feature_details' =>
                                                [
                                                ],
                                        ],
                                    'product_dependent_features' =>
                                        [
                                            'extra_bullet_name'                         => null,
                                            'extra_bullet_icon'                         => null,
                                            'extra_bullet_tooltip'                      => '',
                                            'extra_bullet2_name'                        => null,
                                            'extra_bullet2_icon'                        => null,
                                            'extra_bullet2_tooltip'                     => '',
                                            'extra_bullet3_name'                        => null,
                                            'extra_bullet3_icon'                        => null,
                                            'extra_bullet3_tooltip'                     => '',
                                            'extra_bullet4_name'                        => null,
                                            'extra_bullet4_icon'                        => null,
                                            'extra_bullet4_tooltip'                     => '',
                                            'ignore_health_insurance_search'            => 'no',
                                            'tariff_details_available'                  => 'yes',
                                            'additional_premium'                        => 1.3999999999999999,
                                            'additional_premium_valid_from'             => '2016-01-01',
                                            'next_additional_premium'                   => null,
                                            'next_additional_premium_valid_from'        => null,
                                            'rating'                                    => 1,
                                            'service_phone'                             => 'yes',
                                            'schedule_mediation'                        => 'yes',
                                            'doctor_search_portal'                      => 'yes',
                                            'online_patients_receipt'                   => 'yes',
                                            'homeopathy'                                => 'yes',
                                            'homeopathy_comment'                        => '',
                                            'homeopathic_therapy'                       => 'not_specified',
                                            'homeopathic_therapy_refund'                => '0.00',
                                            'homeopathic_therapy_healthaccount'         => 'not_specified',
                                            'homeopathic_therapy_comment'               => '',
                                            'homeopathic_medicine'                      => 'not_specified',
                                            'homeopathic_medicine_refund'               => '0.00',
                                            'homeopathic_medicine_healthaccount'        => 'not_specified',
                                            'homeopathic_medicine_comment'              => '',
                                            'osteopathy'                                => 'yes',
                                            'osteopathy_refund'                         => '0.00',
                                            'osteopathy_healthaccount'                  => 'not_specified',
                                            'osteopathy_care_provider'                  => '',
                                            'osteopathy_comment'                        => '',
                                            'alternative_cancer_therapy'                => 'yes',
                                            'alternative_cancer_therapy_comment'        => '',
                                            'professional_tooth_cleaning'               => 'no',
                                            'professional_tooth_cleaning_refund'        => '0.00',
                                            'professional_tooth_cleaning_healthaccount' => 'not_specified',
                                            'professional_tooth_cleaning_comment'       => '',
                                            'reduced_dental_prosthesis'                 => 'yes',
                                            'reduced_dental_prosthesis_comment'         => '',
                                            'specific_dental_treatment'                 => 'no',
                                            'specific_dental_treatment_comment'         => '',
                                            'free_choice_hospital'                      => 'yes',
                                            'additional_household_help'                 => 'yes',
                                            'additional_nursing_home_care'              => 'no',
                                            'vaccinations_beyond_by_law'                => 'yes',
                                            'additional_checkups_adult'                 => 'yes',
                                            'miscellaneous_services'                    => 'Reha-Berater; Pflegeberatung; Pflegehotline; Beratungsservice f. Demenzkranke; Med. KompetenzCenter; Apothekenhotline; Pflegeheim-/Pflegedienstnavigator, Servicestelle f. Krebskranke/ Angehörige, Familienbegleiter, Klinikkompass, Krankenhausnavigator',
                                            'miscellaneous_services_formatted'          => null,
                                            'bonus_program'                             => 'yes',
                                            'bonus_program_money_max'                   => '180',
                                            'bonus_program_money_treatment'             => '8',
                                            'retention_program'                         => 'yes',
                                            'premium_refund'                            => 'no',
                                            'artificial_insemination'                   => 'yes',
                                            'additional_pregnancy_examination'          => 'no',
                                            'midwife_standby_service'                   => 'yes',
                                            'additional_youth_examination'              => 'no',
                                            'travel_vaccination'                        => 'yes',
                                            'third_party_course'                        => 'no',
                                            'early_diagnosis_skin_cancer'               => 'yes',
                                            'early_diagnosis_bowel_cancer'              => 'no',
                                            'early_diagnosis_breast_cancer'             => 'no',
                                            'agencies'                                  => [
                                                'num_agencies'           => 2,
                                                'selected_federal_state' => null,
                                            ],
                                            'travel_vaccination_refund'                 => 1.0,
                                            'retention_program_benefit'                 => 1.0,
                                            'retention_program_risk'                    => 1.0,
                                        ],
                                ],
                            'subscription' =>
                                [
                                    'possible' => 'yes',
                                    'external' => '',
                                    'url'      => '&c24_position=33',
                                    'way'      => 'all',
                                ],
                            'price'        =>
                                [
                                    'premium'            => 14.6,
                                    'additional_premium' => 1.3999999999999999,
                                    'total_premium'      => 16,
                                    'contribution_month' =>
                                        [
                                            'amount'   => '36866',
                                            'currency' => 'EUR',
                                        ],
                                    'contribution_year'  =>
                                        [
                                            'amount'   => '442395',
                                            'currency' => 'EUR',
                                        ],
                                ],
                        ],
                ],
            'promotion'    => null,
            'tariffgrade'  =>
                [
                    'feature_id_score_table' => null,
                    'score_grade_table'      =>
                        [
                            1   => '4.30',
                            2   => '4.30',
                            3   => '4.30',
                            4   => '4.30',
                            5   => '4.30',
                            6   => '4.30',
                            7   => '4.30',
                            8   => '4.30',
                            9   => '4.30',
                            10  => '4.30',
                            11  => '4.30',
                            12  => '4.30',
                            13  => '4.30',
                            14  => '4.30',
                            15  => '4.30',
                            16  => '4.30',
                            17  => '4.30',
                            18  => '4.30',
                            19  => '4.30',
                            20  => '3.90',
                            21  => '3.80',
                            22  => '3.60',
                            23  => '3.60',
                            24  => '3.60',
                            25  => '3.50',
                            26  => '3.50',
                            27  => '3.40',
                            28  => '3.40',
                            29  => '3.30',
                            30  => '3.30',
                            31  => '3.20',
                            32  => '3.20',
                            33  => '3.10',
                            34  => '3.10',
                            35  => '3.00',
                            36  => '3.00',
                            37  => '2.90',
                            38  => '2.80',
                            39  => '2.60',
                            40  => '2.50',
                            41  => '2.30',
                            42  => '2.20',
                            43  => '2.00',
                            44  => '1.90',
                            45  => '1.75',
                            46  => '1.60',
                            47  => '1.40',
                            48  => '1.30',
                            49  => '1.20',
                            50  => '1.10',
                            51  => '1.00',
                            52  => '1.00',
                            53  => '1.00',
                            54  => '1.00',
                            55  => '1.00',
                            56  => '1.00',
                            57  => '1.00',
                            58  => '1.00',
                            59  => '1.00',
                            60  => '1.00',
                            61  => '1.00',
                            62  => '1.00',
                            63  => '1.00',
                            64  => '1.00',
                            65  => '1.00',
                            66  => '1.00',
                            67  => '1.00',
                            68  => '1.00',
                            69  => '1.00',
                            70  => '1.00',
                            71  => '1.00',
                            72  => '1.00',
                            73  => '1.00',
                            74  => '1.00',
                            75  => '1.00',
                            76  => '1.00',
                            77  => '1.00',
                            78  => '1.00',
                            79  => '1.00',
                            80  => '1.00',
                            81  => '1.00',
                            82  => '1.00',
                            83  => '1.00',
                            84  => '1.00',
                            85  => '1.00',
                            86  => '1.00',
                            87  => '1.00',
                            88  => '1.00',
                            89  => '1.00',
                            90  => '1.00',
                            91  => '1.00',
                            92  => '1.00',
                            93  => '1.00',
                            94  => '1.00',
                            95  => '1.00',
                            96  => '1.00',
                            97  => '1.00',
                            98  => '1.00',
                            99  => '1.00',
                            100 => '1.00',
                        ],
                ],
            'evaluation'   => null,
        ];

        return [
            'get',
            'calculate/',
            array_merge(
                $this->getGuzzleOptions('calculation'),
                ['query' => $parameters]
            ),
            new Psr7\Response(
                200, [], '{
                "status_code":200,
                "status_message":"OK",
                "data":' . Json\Encoder::encode($mockData) . '
            }'
            ),
        ];
    }

    /**
     * @return response
     */
    protected function getCalculationResponse()
    {

        return new response(
            200, 'OK',
            [
                'parameter'    =>
                    [
                        'id'                           => '5c078fae67bf03fa1a69857151cb11c0',
                        'product_id'                   => PRODUCT_GKV,
                        'partner_id'                   => PARTNER_GKV,
                        'tracking_id'                  => 'checkvers',
                        'tracking_id2'                 => '',
                        'tracking_id3'                 => '',
                        'tracking_id4'                 => '',
                        'mode_id'                      => '',
                        'keep'                         => 'no',
                        'timepoint'                    => '2016-06-22 12:36:36',
                        'remote_address'               => '172.28.128.1',
                        'style'                        => 'check24-bluegrey',
                        'c24logincsplan_id'            => null,
                        'c24loginpointplan_id'         => null,
                        'occupation_group'             => 'employee',
                        'current_insurance_type'       => 'by_law',
                        'zipcode'                      => '22177',
                        'salary'                       => 60000,
                        'federal_state'                => 'Hamburg',
                        'service_phone'                => null,
                        'schedule_mediation'           => null,
                        'doctor_search_portal'         => null,
                        'online_patients_receipt'      => null,
                        'homeopathy'                   => null,
                        'osteopathy'                   => null,
                        'alternative_cancer_therapy'   => null,
                        'professional_tooth_cleaning'  => null,
                        'reduced_dental_prosthesis'    => null,
                        'bonus_program'                => null,
                        'retention_program'            => null,
                        'premium_refund'               => null,
                        'additional_nursing_home_care' => null,
                        'vaccinations'                 => null,
                        'free_choice_hospital'         => null,
                        'additional_checkups_adult'    => null,
                        'additional_household_help'    => null,
                        'current_insurer'              => null,
                        'maxtariffs'                   => 0,
                        'provider_id'                  => 0,
                        'company_id'                   => 0,
                    ],
                'apiparameter' =>
                    [
                        'product_id'                   => PRODUCT_GKV,
                        'update_parameters'            => false,
                        'calculationparameter_id'      => '5c078fae67bf03fa1a69857151cb11c0',
                        'page'                         => 1,
                        'pagesize'                     => 20,
                        'sortfield'                    => 'price',
                        'sortorder'                    => 'asc',
                        'debug'                        => 'no',
                        'caching'                      => 'yes',
                        'stats'                        => 'no',
                        'tariffversion_ids'            => null,
                        'tariffversion_variation_keys' => null,
                        'jsonp_callback'               => '',
                        'ignore_filter'                => 'no',
                        'protocol'                     => 'https',
                        'force_current_timepoint'      => 'no',
                        'show_invisible_tariffs'       => 'no',
                        'calculationparameter_save'    => 'yes',
                        'forecast'                     =>
                            [
                            ],
                    ],
                'paging'       =>
                    [
                        'resultsize'  => 36,
                        'currentpage' => 1,
                        'totalpages'  => 2,
                        'pagesize'    => 20,
                    ],
                'result'       =>
                    [
                        '11-base' =>
                            [
                                'result'       =>
                                    [
                                        'position' => 33,
                                    ],
                                'provider'     =>
                                    [
                                        'id'                         => 9,
                                        'name'                       => 'AOK Rheinland Hamburg',
                                        'comparename'                => null,
                                        'version_id'                 => 129,
                                        'brand'                      => '',
                                        'brand_provider_id'          => null,
                                        'health_insurance_search_id' => 1,
                                        'company'                    => 'AOK Rheinland Hamburg',
                                        'description'                => '',
                                        'logo'                       => '/filestore/provider_logo/72a88558a7f6c911b2e34a1086e2af1b.svg',
                                        'logo2'                      => '',
                                        'logo_comparison'            => '',
                                        'result_grouping'            => '',
                                        'company_id'                 => 9,
                                        'contact'                    =>
                                            [
                                                'phone'      => '089 2000471403',
                                                'phone_info' => '',
                                                'email'      => '',
                                            ],
                                        'address'                    =>
                                            [
                                                'company' => 'AOK Rheinland Hamburg',
                                                'street'  => 'Kasernenstr. 61',
                                                'zipcode' => '40213',
                                                'city'    => 'Düsseldorf',
                                            ],
                                        'customer_satisfaction'      => 'no',
                                        'auto_tariff_selection'      => 'no',
                                        'efeedback_ids'              => null,
                                        'efeedback_review_id'        => 0,
                                        'creditor_identifier'        => 'DE05ZZZ00000018503',
                                        'sepa_text'                  => '',
                                    ],
                                'tariff'       =>
                                    [
                                        'id'                         => 11,
                                        'product_id'                 => PRODUCT_GKV,
                                        'version_id'                 => 11,
                                        'variation_key'              => 'base',
                                        'name'                       => 'AOK Rheinland/Hamburg',
                                        'name_pdf'                   => 'AOK Rheinland/Hamburg',
                                        'validfrom'                  => '',
                                        'tips'                       => null,
                                        'promotion'                  => 'no',
                                        'promotion_title'            => '',
                                        'promotion_position'         => null,
                                        'promotion_bin'              => null,
                                        'hide_rule'                  => '',
                                        'promotion_tariff_id'        => 0,
                                        'description'                => 'Die Gesundheitskasse',
                                        'code'                       => '',
                                        'actioncode'                 => '',
                                        'communication'              => 'normal',
                                        'attachments'                =>
                                            [
                                                'appform'           => null,
                                                'encrypted_appform' => null,
                                            ],
                                        'grade'                      =>
                                            [
                                                'max_points'      => 0,
                                                'total_points'    => 0,
                                                'result'          => 1,
                                                'name'            => 'sehr gut',
                                                'feature_details' =>
                                                    [
                                                    ],
                                            ],
                                        'product_dependent_features' =>
                                            [
                                                'extra_bullet'                              => null,
                                                'extra_bullet_icon'                         => null,
                                                'extra_bullet_tooltip'                      => '',
                                                'extra_bullet2'                             => null,
                                                'extra_bullet2_icon'                        => null,
                                                'extra_bullet2_tooltip'                     => '',
                                                'extra_bullet3'                             => null,
                                                'extra_bullet3_icon'                        => null,
                                                'extra_bullet3_tooltip'                     => '',
                                                'ignore_health_insurance_search'            => 'no',
                                                'tariff_details_available'                  => 'yes',
                                                'additional_premium'                        => 1.3999999999999999,
                                                'additional_premium_valid_from'             => '2016-01-01',
                                                'next_additional_premium'                   => null,
                                                'next_additional_premium_valid_from'        => null,
                                                'rating'                                    => 1,
                                                'service_phone'                             => 'yes',
                                                'schedule_mediation'                        => 'yes',
                                                'doctor_search_portal'                      => 'yes',
                                                'online_patients_receipt'                   => 'yes',
                                                'homeopathy'                                => 'yes',
                                                'homeopathy_comment'                        => '',
                                                'homeopathic_therapy'                       => 'not_specified',
                                                'homeopathic_therapy_refund'                => '0.00',
                                                'homeopathic_therapy_healthaccount'         => 'not_specified',
                                                'homeopathic_therapy_comment'               => '',
                                                'homeopathic_medicine'                      => 'not_specified',
                                                'homeopathic_medicine_refund'               => '0.00',
                                                'homeopathic_medicine_healthaccount'        => 'not_specified',
                                                'homeopathic_medicine_comment'              => '',
                                                'osteopathy'                                => 'yes',
                                                'osteopathy_refund'                         => '0.00',
                                                'osteopathy_healthaccount'                  => 'not_specified',
                                                'osteopathy_comment'                        => '',
                                                'alternative_cancer_therapy'                => 'yes',
                                                'alternative_cancer_therapy_comment'        => '',
                                                'professional_tooth_cleaning'               => 'no',
                                                'professional_tooth_cleaning_refund'        => '0.00',
                                                'professional_tooth_cleaning_healthaccount' => 'not_specified',
                                                'professional_tooth_cleaning_comment'       => '',
                                                'reduced_dental_prosthesis'                 => 'yes',
                                                'reduced_dental_prosthesis_comment'         => '',
                                                'specific_dental_treatment'                 => 'no',
                                                'specific_dental_treatment_comment'         => '',
                                                'free_choice_hospital'                      => 'yes',
                                                'additional_household_help'                 => 'yes',
                                                'additional_nursing_home_care'              => 'no',
                                                'vaccinations_beyond_by_law'                => 'yes',
                                                'additional_checkups_adult'                 => 'yes',
                                                'miscellaneous_services'                    => 'Reha-Berater; Pflegeberatung; Pflegehotline; Beratungsservice f. Demenzkranke; Med. KompetenzCenter; Apothekenhotline; Pflegeheim-/Pflegedienstnavigator, Servicestelle f. Krebskranke/ Angehörige, Familienbegleiter, Klinikkompass, Krankenhausnavigator',
                                                'miscellaneous_services_formatted'          => null,
                                                'bonus_program'                             => 'yes',
                                                'bonus_program_money_max'                   => '180',
                                                'bonus_program_money_treatment'             => '8',
                                                'retention_program'                         => 'yes',
                                                'premium_refund'                            => 'no',
                                            ],
                                    ],
                                'subscription' =>
                                    [
                                        'possible' => 'yes',
                                        'external' => '',
                                        'url'      => '&c24_position=33',
                                        'way'      => 'all',
                                    ],
                                'price'        =>
                                    [
                                        'premium'            => 14.6,
                                        'additional_premium' => 1.3999999999999999,
                                        'total_premium'      => 16,
                                        'contribution_month' =>
                                            [
                                                'amount'   => '36866',
                                                'currency' => 'EUR',
                                            ],
                                        'contribution_year'  =>
                                            [
                                                'amount'   => '442395',
                                                'currency' => 'EUR',
                                            ],
                                    ],
                            ],
                    ],
                'promotion'    => null,
                'tariffgrade'  =>
                    [
                        'feature_id_score_table' => null,
                        'score_grade_table'      =>
                            [
                                1   => '4.30',
                                2   => '4.30',
                                3   => '4.30',
                                4   => '4.30',
                                5   => '4.30',
                                6   => '4.30',
                                7   => '4.30',
                                8   => '4.30',
                                9   => '4.30',
                                10  => '4.30',
                                11  => '4.30',
                                12  => '4.30',
                                13  => '4.30',
                                14  => '4.30',
                                15  => '4.30',
                                16  => '4.30',
                                17  => '4.30',
                                18  => '4.30',
                                19  => '4.30',
                                20  => '3.90',
                                21  => '3.80',
                                22  => '3.60',
                                23  => '3.60',
                                24  => '3.60',
                                25  => '3.50',
                                26  => '3.50',
                                27  => '3.40',
                                28  => '3.40',
                                29  => '3.30',
                                30  => '3.30',
                                31  => '3.20',
                                32  => '3.20',
                                33  => '3.10',
                                34  => '3.10',
                                35  => '3.00',
                                36  => '3.00',
                                37  => '2.90',
                                38  => '2.80',
                                39  => '2.60',
                                40  => '2.50',
                                41  => '2.30',
                                42  => '2.20',
                                43  => '2.00',
                                44  => '1.90',
                                45  => '1.75',
                                46  => '1.60',
                                47  => '1.40',
                                48  => '1.30',
                                49  => '1.20',
                                50  => '1.10',
                                51  => '1.00',
                                52  => '1.00',
                                53  => '1.00',
                                54  => '1.00',
                                55  => '1.00',
                                56  => '1.00',
                                57  => '1.00',
                                58  => '1.00',
                                59  => '1.00',
                                60  => '1.00',
                                61  => '1.00',
                                62  => '1.00',
                                63  => '1.00',
                                64  => '1.00',
                                65  => '1.00',
                                66  => '1.00',
                                67  => '1.00',
                                68  => '1.00',
                                69  => '1.00',
                                70  => '1.00',
                                71  => '1.00',
                                72  => '1.00',
                                73  => '1.00',
                                74  => '1.00',
                                75  => '1.00',
                                76  => '1.00',
                                77  => '1.00',
                                78  => '1.00',
                                79  => '1.00',
                                80  => '1.00',
                                81  => '1.00',
                                82  => '1.00',
                                83  => '1.00',
                                84  => '1.00',
                                85  => '1.00',
                                86  => '1.00',
                                87  => '1.00',
                                88  => '1.00',
                                89  => '1.00',
                                90  => '1.00',
                                91  => '1.00',
                                92  => '1.00',
                                93  => '1.00',
                                94  => '1.00',
                                95  => '1.00',
                                96  => '1.00',
                                97  => '1.00',
                                98  => '1.00',
                                99  => '1.00',
                                100 => '1.00',
                            ],
                    ],
                'evaluation'   => null,
            ]
        );
    }
}