<header>
    <?php echo $this->partial('common/head.phtml'); ?>
</header>

<div id="c24-content">

    <?php echo $this->form()->openTag($form); ?>

    <input type="hidden" value="month" id="paymentperiod_month" name="paymentperiod" />

    <div class="c24-landingpage" id="c24-landingpage-power">

        <div class="c24-landingpage-top">

            <div class="c24-landingpage-image">

                <div id="c24-landingpage-page-title">Stromvergleich Testsieger</div>
                <div class="c24-tuev"></div>
                <div class="c24-testsieger-computer"></div>

                <ul id="c24-landingpage-promolist">
                    <li>Über 1.000 Stromanbieter</li>
                    <li>Über 12.500 Tarife</li>
                    <li>Bis zu 720 Euro sparen</li>
                </ul>

            </div>

        </div>

        <div id="c24-landingpage-content">

            <div id="c24-landingpage-input-box">

                <?php echo $form->render($form->generate_tel_field('zipcode', 'Postleitzahl *')); ?>

                <?php

                    $display_city = !empty($form->get('city')->getMessages());

                    echo $form->render($form->generate_select_field('city', 'Ort *', [], $display_city));

                ?>

                <div class="c24-clearfix">

                    <label id="c24-select-bar-headline" class="c24-block-label-top c24-label">Anzahl Personen im Haushalt</label>

                    <div id="c24-totalconsumption-bar" class="c24-clearfix">
                        <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-first" id="c24-human1" data-totalconsumption-value="2000">
                            <div class="c24-human-image c24-human-image-1"></div>
                        </div>
                        <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-active" id="c24-human2" data-totalconsumption-value="3500">
                            <div class="c24-human-image c24-human-image-1"></div>
                            <div class="c24-human-image c24-human-image-2"></div>
                        </div>
                        <div class="c24-totalconsumption-bar-item" id="c24-human3" data-totalconsumption-value="4250">
                            <div class="c24-human-image c24-human-image-1"></div>
                            <div class="c24-human-image c24-human-image-2"></div>
                            <div class="c24-human-image c24-human-image-3"></div>
                        </div>
                        <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-last" id="c24-human4" data-totalconsumption-value="5000">
                            <div class="c24-human-image c24-human-image-1"></div>
                            <div class="c24-human-image c24-human-image-2"></div>
                            <div class="c24-human-image c24-human-image-3"></div>
                            <div class="c24-human-image c24-human-image-4"></div>
                        </div>
                    </div>

                </div>

                <?php

                    $select_visible = in_array(
                        $form->get('totalconsumption_select')->getValue(),
                        [0, 2000, 3500, 5000, 8000]
                    );

                    echo $form->render($form->generate_select_field('totalconsumption_select', 'Stromverbrauch *', [], $select_visible));

                    echo $form->render($form->generate_tel_field('totalconsumption_total', 'Stromverbrauch *', [], !$select_visible));

                ?>

            </div>

            <input type="submit" value="jetzt vergleichen" class="c24-button-plain-blue full_button">

            <?php if (\classes\helper\shopping_campaign::is_active()): ?>
            <div class="c24-shopping-campaign-link">
                + 20 € Einkaufsgutschein für Elektronik & Haushalt
            </div>
            <?php endif; ?>

        </div>

    </div>

    <?php
        echo $this->form()->closeTag();
    ?>

</div>

<?php if (\classes\helper\shopping_campaign::is_active()): ?>
    <div class="c24-shopping-campaign-bubble"></div>
<?php endif; ?>

<div id="c24-gt-pixel"><?php echo $generaltracking_pixel; ?></div>

<script type="text/javascript">
    var suewag = false;
</script>