<div id="c24-landingpage-head">

    <div id="c24-landingpage-head-right">



        <?php
        if ($this->layout()->show_hotline == true) :
            ?>
            <table>
                <tr>
                    <td rowspan="2">
                        <img src="/images/landingpage/hotline-icon-25x33.png" style="width: 16px;" />
                    </td>
                    <td>
                        <span class="c24-landingpage-kostenlose">Kostenlose Beratung</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="tel:0800755455430" class="c24-color c24-hotline-link">0800 - 755 455 430</a>
                    </td>
                </tr>
            </table>


        <?php
        endif;
        ?>
    </div>

</div>

<div id="c24-landingpage-page-title" class="c24-color">Süwag-Strom bei CHECK24</div>

<?php
echo $this->form()->openTag($form);
?>

<div class="c24-landingpage c24-landingpage-suewag" id="c24-landingpage-power">

    <div id="c24-suewag94-logo"></div>

    <div id="c24-landingpage-right">

        <ul id="c24-landingpage-promolist">
            <li>Exklusiv: bis zu 250 € Sofortbonus</li>
            <li>Preisfixierung bis zum 31.12.2015</li>
            <li>94% Weiterempfehlungsquote</li>
        </ul>

        <div id="c24-landingpage-input-box">

            <?php echo $form->render($form->generate_tel_field('zipcode', 'Postleitzahl *')); ?>

            <?php

                $display_city = !empty($form->get('city')->getMessages());

                echo $form->render($form->generate_select_field('city', 'Ort *', [], $display_city));

            ?>

            <label id="c24-select-bar-headline" class="c24-block-label-top c24-label">Anzahl Personen im Haushalt</label>

            <div id="c24-totalconsumption-bar" class="c24-clearfix">
                <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-first" id="c24-human1" data-totalconsumption-value="2000">
                    <div class="c24-human-image c24-human-image-1"></div>
                </div>
                <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-active" id="c24-human2" data-totalconsumption-value="3500">
                    <div class="c24-human-image c24-human-image-1"></div>
                    <div class="c24-human-image c24-human-image-2"></div>
                </div>
                <div class="c24-totalconsumption-bar-item" id="c24-human3" data-totalconsumption-value="4250">
                    <div class="c24-human-image c24-human-image-1"></div>
                    <div class="c24-human-image c24-human-image-2"></div>
                    <div class="c24-human-image c24-human-image-3"></div>
                </div>
                <div class="c24-totalconsumption-bar-item c24-totalconsumption-bar-item-last" id="c24-human4" data-totalconsumption-value="5000">
                    <div class="c24-human-image c24-human-image-1"></div>
                    <div class="c24-human-image c24-human-image-2"></div>
                    <div class="c24-human-image c24-human-image-3"></div>
                    <div class="c24-human-image c24-human-image-4"></div>
                </div>
            </div>

            <?php echo $form->render($form->generate_tel_field('totalconsumption', 'Stromverbrauch *', [], true)); ?>

            <input type="hidden" value="month"  id="paymentperiod_month" name="paymentperiod" />
            <input type="hidden" value="11012"  id="provider_id" name="provider_id" />
            <input type="hidden" value="CH24_E_BANsuewag"  id="tracking_id" name="tracking_id" />

        </div>

        <input type="submit" value="jetzt vergleichen" class="c24-button-plain-blue full_button">

        <div class="c24-suewag-refer-to-product">
            <a class="c24-color" href="<?php echo $this->gas_link; ?>?tid=CH24_E_BANsuewag">
                <span>zu Süwag-Gas</span>
            </a>
        </div>

    </div>

</div>

<?php
echo $this->form()->closeTag();
?>

<div id="c24-gt-pixel">
    <?php
    echo $generaltracking_pixel;
    ?>
</div>

<script type="text/javascript">
    var suewag = true;
</script>