<?php if ($this->is_employee && !$this->is_child): ?>

    <div class="wrapper-price">
        <span class="price-text">Beitrag mtl.</span>
        <span class="result-price">
            <?php echo $this->currencyformat($this->tariff->get_paymentperiod_size()); ?>
        </span>
    </div>

    <div class="wrapper-employee-part">
        <span class="employee-part-text">Ihr Anteil</span>
        <span class="employee-part" data-employee-part="<?php echo $this->tariff->get_paymentperiod_size_net_contribution(); ?>">
            <?php echo $this->currencyformat($this->tariff->get_paymentperiod_size_net_contribution()) ?>
        </span>
    </div>

    <?php $wrapper_saving_price_class = ($this->tariff->get_paymentperiod_size_net_saving() > 0) ? 'on' : 'off'; ?>
    <?php $saving_price_text          = $wrapper_saving_price_class == 'on' ? 'Gespart pro Jahr**' : ''; ?>
    <?php $saving_price_value         = $wrapper_saving_price_class == 'on' ? $this->currencyformat($this->tariff->get_paymentperiod_size_net_saving_per_year()) : ''; ?>

    <div class="wrapper-saving-price <?php echo $wrapper_saving_price_class ?>">
        <span class="saving-price-text">
            <?php echo $saving_price_text ?>
        </span>
        <span class="saving-price">
             <?php echo $saving_price_value ?>
        </span>
    </div>

<?php else: ?>

    <div class="wrapper-employee-part price" style="text-align: right;">
        <span class="not-empoyee-part" data-not-employee-part="<?php echo $this->tariff->get_paymentperiod_size(); ?>">
            <?php echo $this->currencyformat($this->tariff->get_paymentperiod_size())?>
        </span>
        <span class="employee-part-text">monatlich</span>
    </div>

<?php endif; ?>