<div class="c24-result-tariff-header">
    <div class="c24-result-tariff-logo">
        <img src="<?php echo $this->tariff->get_provider_logo('svg'), false; ?>"
             alt="<?php echo $this->tariff->get_provider_comparename(); ?>">
    </div>
    <div class="c24-result-tariff-name">
        <ul class='c24-result-tariff-name-list'>
            <li class="c24-result-tariff-name-list-content">
            <?php
                echo 'Tarif: ' . $this->tariffnameFormater($this->tariff->get_tariff_name());
            ?>
            </li>
            <?php
                $icon = $this->partial('mclient/view/default/pkv/tariff_name_tooltip_partial.php',[
                    'title'   => 'Tarifbausteine',
                    'content' => $this->tariffnameFormater($this->tariff->get_tariff_name())
                ]);
            ?>
            <div class="tooltip-wrapper"><?php echo $icon ?></div>
        </ul>
    </div>
</div>

<?php
    $favorite_contribution = ($this->calculationparameter->get_profession() == 'employee' && $this->calculationparameter->get_insured_person() == 'adult')
        ? $this->tariff->get_paymentperiod_size_net_contribution()
        : $this->tariff->get_paymentperiod_size();

    $is_favorite_class = $this->tariff->is_favorite_tariff() ? 'is-favorite' : '';
?>

<div class="c24-tariff-overview-right">
    <div class="my-favorite <?php echo $is_favorite_class; ?>"
         data-favorite-calculation-parameter-id="<?php echo $this->calculationparameter->get_id(); ?>"
         data-favorite-tariffversion-id="<?php echo $this->tariff->get_tariff_version_id(); ?>"
         data-favorite-tariffversion-variaton-key="<?php echo $this->tariff->get_tariff_variation_key(); ?>"
         data-favorite-is-promo-tariff="<?php echo !empty($this->tariff->get_promotion_type()) ? 'yes' : 'no'; ?>"
         data-favorite-promotion-type="<?php echo $this->tariff->get_promotion_type(); ?>"
         data-favorite-is-gold-grade="<?php echo ($this->tariff->is_gold_grade() == 1) ? 'yes' : 'no'; ?>"
         data-favorite-contribution="<?php echo $favorite_contribution; ?>"
        >
    </div>
</div>

<?php
$profession     = $this->profession;
$insured_person = $this->insured_person;

include 'module/classes/calculation/mclient/view/default/pv/tariff_interferer.phtml';

$tariff_grade_helper = new \classes\calculation\client\controller\helper\generate_tariffgrade_pkv($this->tariff);
//@TODO need to execute this getter function to be able to retrieve the grade_text_class information
$tariff_grade_helper->get_grade_description($this->tariff->get_tariff_features()['global']['content']['grade']);
$grade_text_class = $tariff_grade_helper->get_grade_text_class();
?>

<div class="c24-wrapper-tariff-informations">
    <div class="c24-result-row-middle">
        <div class="c24-tariff-info-row">
        <?php echo $this->render('default/pv/tariffinformation_price.phtml'); ?>
        </div>

        <?php if ($this->tariff->is_gold_grade()): ?>
        <div class="grade golden grade_tariffheader ">
        <?php else: ?>
        <div class="grade grade_tariffheader">
        <?php endif; ?>
                <span class="gradeNumber"><?php echo $this->tariff_feature_grade; ?></span>
                <span class="tarifflabel">Tarifnote</span>
                <span class="gradeText <?php echo $grade_text_class;?> ">
                    <?php

                    if ($this->tariff->is_gold_grade()) {
                        echo 'Testsieger';
                    } else {
                        echo $this->tariff_feature_description;
                    }

                ?></span>
        </div>
    </div>
</div>