<div class="jumbotron">
    <h1>Hellow world!</h1>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Check my Blog</h3>
            </div>
            <div class="panel-body">
                <p>Not yet finalized, but already something interesting to see :)</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('blog') ?>"><?php echo $this->translate('My Blog') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

</div>
