<div class="c24-content-row-block-infobox">

    <div class="c24-content-row-info-text">

        <div class="c24-content-row-info-text-content">
            <?php echo $help_info_content; ?>
        </div>

        <?php if (!empty($help_info_hint)) {?>
        <div class="c24-content-row-info-hint-content">
            <h2><i class="fa fa-exclamation-circle"></i> Tipp&nbsp;</h2>
            <?php echo $help_info_hint; ?>
        </div>
        <?php } ?>

        <div class="c24-info-close-row">
            <i class="fa fa-angle-up"></i>
        </div>

    </div>

</div>
