<h1>Was unsere Kunden sagen</h1>

<div id="c24-efeedback-comments">
    <?php foreach ($reviews AS $review): ?>
        <div class="c24-user-comments">
            <div class="c24-user-comment-date">
                <?php echo $review->created_at;?>
            </div>

            <?php if ($review->comment_positive): ?>
                <div class="c24-user-comment">
                    <div class="positive"><i class="fa fa-check"></i></div>
                    <div class="comment">
                        <?php echo $review->comment_positive ?>
                    </div>
                </div>
            <?php endif;?>

            <?php if ($review->comment_negative): ?>
                <div class="c24-user-comment">
                    <div class="negative"><i class="fa fa-times"></i></div>
                    <div class="comment">
                        <?php echo $review->comment_negative ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="c24-user-comment-score">
                <?php echo $this->stars()->render($review->rating / 2); ?>
            </div>
        </div>

    <?php endforeach; ?>
</div>

<p id="no_more_customerfeedback" class="no_more_customerfeedback">
    <span><i class="fa fa-info"></i> Keine weiteren Bewertungen vorhanden.</span>
</p>

<a id="close_customerfeedbacks" class="c24-button c24-accordion-title">
    Kundenbewertungen schließen
</a>

<a id="more_customerfeedbacks" class="c24-button">weitere Kundenbewertungen anzeigen</a>